//! Rendering of the individual output files. All HCL goes through `hcl::format`; the
//! only string work here is comments, file headers and `terraform fmt`-style alignment.

use crate::emit::{ManualEntry, OutputSpec, VarSpec};
use crate::tool::Profile;
use hcl::{Block, Expression, Identifier, Object, ObjectKey};
use ttg_catalog::{Catalog, ProviderDef};
use ttg_core::Project;

fn fmt_block(b: &Block) -> String {
    let s = hcl::format::to_string(b).expect("hcl formatting cannot fail for a built tree");
    let mut s = align_attributes(&s).replace("{  }", "{}");
    while s.ends_with("\n\n") {
        s.pop();
    }
    if !s.ends_with('\n') {
        s.push('\n');
    }
    s
}

/// A `.tf` file of resource blocks, each entity introduced by a comment.
pub fn render_resource_file(header: &str, entries: &[(String, Vec<Block>)]) -> String {
    let mut out = String::from(header);
    for (comment, blocks) in entries {
        out.push('\n');
        out.push_str(&format!("# --- {comment}\n"));
        for b in blocks {
            out.push_str(&fmt_block(b));
            out.push('\n');
        }
    }
    out
}

pub fn render_variables(header: &str, vars: &[&VarSpec]) -> String {
    let mut out = String::from(header);
    if vars.is_empty() {
        out.push_str("\n# No input variables are required for this configuration.\n");
        return out;
    }
    for v in vars {
        let mut b = Block::builder("variable")
            .add_label(v.name.as_str())
            .add_attribute(("type", raw(&v.var_type)));
        if !v.description.is_empty() {
            b = b.add_attribute(("description", v.description.as_str()));
        }
        if let Some(d) = &v.default {
            b = b.add_attribute(("default", d.clone()));
        }
        if v.sensitive {
            b = b.add_attribute(("sensitive", true));
        }
        out.push('\n');
        out.push_str(&fmt_block(&b.build()));
    }
    out
}

pub fn render_outputs(header: &str, outputs: &[OutputSpec]) -> String {
    let mut out = String::from(header);
    if outputs.is_empty() {
        out.push_str("\n# No outputs are declared for this configuration.\n");
        return out;
    }
    for o in outputs {
        let mut b = Block::builder("output")
            .add_label(o.name.as_str())
            .add_attribute(("description", o.description.as_str()))
            .add_attribute(("value", o.value.clone()));
        if o.sensitive {
            b = b.add_attribute(("sensitive", true));
        }
        let b = b.build();
        out.push('\n');
        out.push_str(&fmt_block(&b));
    }
    out
}

pub fn render_versions(header: &str, profile: &Profile, pdef: &ProviderDef) -> String {
    let mut entry = Object::new();
    entry.insert(
        ObjectKey::Identifier(Identifier::unchecked("source")),
        Expression::String(
            profile.provider_source(&pdef.provider.source_namespace, &pdef.provider.source_name),
        ),
    );
    entry.insert(
        ObjectKey::Identifier(Identifier::unchecked("version")),
        Expression::String(pdef.provider.version_constraint.clone()),
    );
    let rp = Block::builder("required_providers")
        .add_attribute((pdef.provider.local_name(), Expression::Object(entry)))
        .build();
    let tf = Block::builder("terraform")
        .add_attribute(("required_version", profile.required_version()))
        .add_block(rp)
        .build();
    format!("{header}\n{}", fmt_block(&tf))
}

pub fn render_providers(header: &str, block: &Block) -> String {
    format!("{header}\n{}", fmt_block(block))
}

pub fn render_backend(header: &str, block: &Block) -> String {
    format!(
        "{header}# State backend configuration. Adjust before `init`.\n\n{}",
        fmt_block(block)
    )
}

pub fn render_manual_steps(
    p: &Project,
    cat: &Catalog,
    provider_display: &str,
    steps: &[ManualEntry],
    vars: &indexmap::IndexMap<String, VarSpec>,
) -> String {
    let mut out = String::new();
    out.push_str(&format!(
        "# Manual steps — {provider_display}\n\n\
         Generated by TerraTofu GUI from project **{}**. The configuration in this directory \
         deploys, but the diagram contains intent that the {provider_display} mapping could not \
         fully express. Work through every item below.\n",
        p.name
    ));
    let mut n = 0;
    for s in steps {
        n += 1;
        out.push_str(&format!("\n## {n}. {}\n\n", s.title));
        if !s.body.is_empty() {
            out.push_str(s.body.trim());
            out.push('\n');
        }
        // For "create by hand" entries, list the configured values and the variables to fill.
        if let Some(id) = &s.entity {
            if s.title.starts_with("Create ") {
                if let Some(e) = p.entity(id) {
                    let def = cat.resource(e.resource_type);
                    out.push_str("\nConfigured in the diagram:\n\n");
                    out.push_str(&format!("- name: `{}`\n", e.name));
                    out.push_str(&format!("- abstract type: `{}`\n", e.resource_type));
                    if let Some(parent) = e.parent {
                        out.push_str(&format!("- inside: `{}`\n", p.hcl_name(parent)));
                    }
                    for (k, v) in e.config {
                        let label = def
                            .and_then(|d| d.fields.iter().find(|f| &f.name == k))
                            .map(|f| f.label().to_string())
                            .unwrap_or(k.clone());
                        out.push_str(&format!("- {label}: `{v}`\n"));
                    }
                    for (prov, cfg) in e.provider_config {
                        for (k, v) in cfg {
                            if !v.is_empty() {
                                out.push_str(&format!("- {k} ({prov}): `{v}`\n"));
                            }
                        }
                    }
                    let slug = p.hcl_name(id);
                    let needed: Vec<&VarSpec> = vars
                        .values()
                        .filter(|v| v.name.starts_with(&format!("{slug}_")) && v.default.is_none())
                        .collect();
                    if !needed.is_empty() {
                        out.push_str("\nAfter creating it, supply these input variables (e.g. in `terraform.tfvars`):\n\n");
                        for v in needed {
                            out.push_str(&format!("- `{}` — {}\n", v.name, v.description));
                        }
                    }
                }
            }
        }
    }
    out
}

pub fn render_readme(p: &Project, profile: &Profile, pdef: &ProviderDef, has_manual: bool) -> String {
    let bin = profile.binary();
    let mut s = format!(
        "# {} — {} ({})\n\n\
         Generated by TerraTofu GUI. Provider: **{}** (`{}` {}).\n\n\
         ## Usage\n\n```\n{bin} init\n{bin} validate\n{bin} plan\n{bin} apply\n```\n\n\
         Input variables are declared in `variables.tf`; put values in a `terraform.tfvars` file \
         or pass `-var`. Provider docs: {}\n",
        p.name,
        pdef.provider.display_name,
        profile.display_name(),
        pdef.provider.display_name,
        profile.provider_source(&pdef.provider.source_namespace, &pdef.provider.source_name),
        pdef.provider.version_constraint,
        profile.registry_url(&pdef.provider.source_namespace, &pdef.provider.source_name),
    );
    if has_manual {
        s.push_str("\n> **Read `MANUAL_STEPS.md`** — parts of the diagram must be completed by hand.\n");
    }
    s
}

fn raw(s: &str) -> Expression {
    crate::emit::raw_expr(s)
}

/// Pad `key =` runs so `=` signs line up, mirroring `terraform fmt`. A run is a sequence of
/// consecutive attribute lines at the same indentation.
pub fn align_attributes(s: &str) -> String {
    let lines: Vec<&str> = s.lines().collect();
    let mut out: Vec<String> = Vec::with_capacity(lines.len());
    let mut i = 0;
    while i < lines.len() {
        let Some((indent, _)) = attr_parts(lines[i]) else {
            out.push(lines[i].to_string());
            i += 1;
            continue;
        };
        // collect the run
        let mut j = i;
        let mut width = 0;
        while j < lines.len() {
            match attr_parts(lines[j]) {
                Some((ind, key)) if ind == indent => {
                    width = width.max(key.len());
                    j += 1;
                }
                _ => break,
            }
        }
        for line in &lines[i..j] {
            let (ind, key) = attr_parts(line).unwrap();
            let rest = line[ind + key.len()..].trim_start();
            out.push(format!("{}{:width$} {}", &line[..ind], key, rest, width = width));
        }
        i = j;
    }
    let mut r = out.join("\n");
    if s.ends_with('\n') {
        r.push('\n');
    }
    r
}

/// (indent width, key) if the line looks like `  key = ...`.
fn attr_parts(line: &str) -> Option<(usize, &str)> {
    let indent = line.len() - line.trim_start().len();
    let body = &line[indent..];
    let key_end = body
        .find(|c: char| !(c.is_ascii_alphanumeric() || c == '_' || c == '-'))
        .unwrap_or(body.len());
    if key_end == 0 {
        return None;
    }
    let after = body[key_end..].trim_start();
    if after.starts_with("= ") || after == "=" {
        Some((indent, &body[..key_end]))
    } else {
        None
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn align() {
        let s = "resource \"a\" \"b\" {\n  id = 1\n  cidr_block = \"x\"\n\n  nested {\n    a = 1\n  }\n}\n";
        let a = align_attributes(s);
        assert!(a.contains("  id         = 1\n  cidr_block = \"x\""));
        assert!(a.contains("    a = 1"));
    }
}
