//! The Kubernetes half of an export. With `settings.kubernetes_manifests` on, a `k8s/`
//! directory beside the Terraform holds, per Kubernetes Workload, the Namespace,
//! ServiceAccount, Deployment, Service, volumes, autoscaling and load-balancer binding the
//! diagram already implies — the part the workload's manual steps used to ask for.
//!
//! Values only Terraform knows after `apply` (a queue URL, a file system id, a target
//! group ARN) are never guessed. Each becomes a `k8s_<slug>_<key>` output in
//! `outputs.tf` and a `${k8s_<slug>_<key>}` token in the YAML, and `k8s/render.sh` /
//! `k8s/render.ps1` copy the manifests into `k8s/rendered/` with every token replaced by
//! its output. What a linked resource hands a workload is declared in that resource's
//! definition (`[providers.<id>.connection]`, MAPPING_FORMAT.md §2.7), so this module
//! only knows the workload's own links and the per-provider identity conventions.
//!
//! The YAML is written by a small emitter over `serde_json::Value` (whose maps keep
//! insertion order), so two exports of the same diagram are byte-identical.

use crate::diagnostics::{self, relation_targets_of_type};
use crate::emit::{ManualEntry, OutputSpec};
use crate::tool::Profile;
use crate::GenError;
use hcl::Expression;
use indexmap::IndexMap;
use serde_json::{json, Map, Value as J};
use std::collections::{BTreeSet, HashSet};
use ttg_catalog::{Catalog, Transform};
use ttg_core::{EntityRef, Id, Project, Relation};

/// The directory the manifests are written to, relative to the export directory.
pub const DIR: &str = "k8s";

/// The tag a Deployment uses while the workload has no **Image tag**. It is a legal tag,
/// so the file applies, and an obviously wrong one, so the pod fails to pull rather than
/// silently running `latest`; a manual step says to set it.
pub const IMAGE_TAG_PLACEHOLDER: &str = "set-image-tag";

/// What the manifests ask the Terraform side to resolve.
pub(crate) enum Want<'s> {
    /// `connection.<key>` of an entity, resolved on that entity.
    Connection { target: &'s str, key: &'s str },
    /// A provider-level variable, e.g. the AWS region KEDA's SQS scaler needs.
    Var(&'s str),
}

/// Everything the Kubernetes export adds to one provider's file set.
pub(crate) struct Manifests {
    /// `k8s/…` path -> content.
    pub files: Vec<(String, String)>,
    /// One output per `${…}` token the manifests contain.
    pub outputs: Vec<OutputSpec>,
    pub manual: Vec<ManualEntry>,
}

struct Token {
    value: Expression,
    description: String,
    /// Whose value it is, so two resources whose names collide are caught.
    owner: (String, String),
}

/// One environment variable, for the README table.
struct EnvRow {
    name: String,
    value: String,
    from: String,
}

struct Summary {
    name: String,
    namespace: String,
    file: String,
    image: String,
    env: Vec<EnvRow>,
    objects: Vec<String>,
}

struct Gen<'a, F> {
    p: &'a Project,
    cat: &'a Catalog,
    provider: &'a str,
    resolve: F,
    tokens: IndexMap<String, Token>,
    manual: Vec<ManualEntry>,
    notes: Vec<String>,
    keda: bool,
    lb_controller: bool,
}

/// Build the `k8s/` files for one provider. `resolve` turns a wanted value into the HCL
/// expression the matching output carries (the emitter's reference machinery, so a
/// manual target becomes an input variable exactly as it would anywhere else).
pub(crate) fn generate<F>(
    p: &Project,
    cat: &Catalog,
    provider: &str,
    profile: Profile,
    resolve: F,
) -> Result<Manifests, GenError>
where
    F: FnMut(Want<'_>) -> Result<Option<Expression>, GenError>,
{
    let mut workloads: Vec<EntityRef> = p
        .entities()
        .into_iter()
        .filter(|e| e.resource_type == "kubernetes_workload" && !e.manual)
        .filter(|e| cat.mapping(e.resource_type, provider).is_some())
        .collect();
    workloads.sort_by_key(|e| k8s_name(e.name));
    if workloads.is_empty() {
        return Ok(Manifests {
            files: Vec::new(),
            outputs: Vec::new(),
            manual: Vec::new(),
        });
    }
    let provider_display = cat
        .provider(provider)
        .map(|d| d.provider.display_name.clone())
        .unwrap_or(provider.to_string());
    let mut g = Gen {
        p,
        cat,
        provider,
        resolve,
        tokens: IndexMap::new(),
        manual: Vec::new(),
        notes: Vec::new(),
        keda: false,
        lb_controller: false,
    };

    let header = format!(
        "# Generated by TerraTofu GUI from project \"{}\" ({provider_display}).\n\
         # The k8s_* placeholders are Terraform outputs: run render.sh or render.ps1\n\
         # after `{} apply` and apply the files in rendered/, not these.\n",
        p.name,
        profile.binary()
    );
    let mut files = Vec::new();
    let mut namespaces = BTreeSet::new();
    let mut summaries = Vec::new();
    for w in &workloads {
        let (docs, summary) = g.workload(w)?;
        namespaces.insert(summary.namespace.clone());
        files.push((format!("{DIR}/{}", summary.file), render_docs(&header, &docs)));
        summaries.push(summary);
    }
    // `kubectl apply -f <dir>` goes through the files in name order, so the namespaces
    // come first. The two every cluster already has are left alone.
    let ns_docs: Vec<J> = namespaces
        .iter()
        .filter(|n| n.as_str() != "default" && !n.starts_with("kube-"))
        .map(|n| {
            json!({
                "apiVersion": "v1",
                "kind": "Namespace",
                "metadata": { "name": n, "labels": { "app.kubernetes.io/managed-by": "terratofu-gui" } },
            })
        })
        .collect();
    if !ns_docs.is_empty() {
        files.insert(
            0,
            (
                format!("{DIR}/00-namespaces.yaml"),
                render_docs(&header, &ns_docs),
            ),
        );
    }

    let token_names: Vec<String> = g.tokens.keys().cloned().collect();
    files.push((format!("{DIR}/render.sh"), render_sh(&token_names, profile)));
    files.push((format!("{DIR}/render.ps1"), render_ps1(&token_names, profile)));
    files.push((
        format!("{DIR}/README.md"),
        g.readme(&provider_display, profile, &summaries, &files),
    ));

    if g.keda || g.lb_controller {
        let (title, body) = g.controllers_step();
        g.manual.push(ManualEntry {
            entity: None,
            title,
            body,
        });
    }
    let outputs = g
        .tokens
        .into_iter()
        .map(|(name, t)| OutputSpec {
            name,
            value: t.value,
            description: t.description,
            sensitive: false,
        })
        .collect();
    Ok(Manifests {
        files,
        outputs,
        manual: g.manual,
    })
}

/// A Kubernetes object name from a display name: `ASR Worker` -> `asr-worker`.
pub fn k8s_name(name: &str) -> String {
    let s = Transform::Kebab.apply(name);
    let s = s.trim_matches('-');
    let s: String = s.chars().take(63).collect();
    s.trim_end_matches('-').to_string()
}

/// `api key` -> `API_KEY`, the entity part of an environment variable name.
fn env_part(name: &str) -> String {
    ttg_core::slugify(name).trim_start_matches('_').to_uppercase()
}

fn str_field(e: &EntityRef, name: &str) -> Option<String> {
    e.field(name)
        .filter(|v| !v.is_empty())
        .map(|v| v.display().trim().to_string())
}

impl<'a, F> Gen<'a, F>
where
    F: FnMut(Want<'_>) -> Result<Option<Expression>, GenError>,
{
    fn display(&self, e: &EntityRef) -> String {
        self.cat
            .resource(e.resource_type)
            .map(|d| d.resource.display_name.clone())
            .unwrap_or(e.resource_type.to_string())
    }

    fn int_field(&self, e: &EntityRef, name: &str) -> Option<i64> {
        diagnostics::field_or_default(self.cat, self.provider, e, name, false).and_then(|v| v.as_int())
    }

    fn targets(&self, e: &EntityRef, kind: Relation, ty: &str) -> Vec<Id> {
        relation_targets_of_type(self.p, self.cat, e, kind, Some(ty))
    }

    /// `${k8s_<slug>_<key>}` for a connection value of `target`, registering the output
    /// it is rendered from. `None` when the target's mapping has no such value (or it
    /// resolves to nothing on this provider).
    fn token(&mut self, target: &str, key: &str) -> Result<Option<String>, GenError> {
        let name = format!("k8s_{}_{}", self.p.hcl_name(target), key.to_lowercase());
        let owner = (target.to_string(), key.to_string());
        if let Some(t) = self.tokens.get(&name) {
            if t.owner != owner {
                return Err(self.collision(&name));
            }
            return Ok(Some(format!("${{{name}}}")));
        }
        let Some(value) = (self.resolve)(Want::Connection { target, key })? else {
            return Ok(None);
        };
        let e = self.p.entity(target).expect("a linked entity exists");
        let description = format!(
            "{key} of the {} \"{}\", read by the Kubernetes manifests",
            self.display(&e),
            e.name
        );
        self.tokens.insert(
            name.clone(),
            Token {
                value,
                description,
                owner,
            },
        );
        Ok(Some(format!("${{{name}}}")))
    }

    /// `${k8s_<var>}` for a provider-level variable.
    fn var_token(&mut self, var: &str) -> Result<Option<String>, GenError> {
        let name = format!("k8s_{var}");
        let owner = (String::new(), var.to_string());
        if let Some(t) = self.tokens.get(&name) {
            if t.owner != owner {
                return Err(self.collision(&name));
            }
            return Ok(Some(format!("${{{name}}}")));
        }
        let Some(value) = (self.resolve)(Want::Var(var))? else {
            return Ok(None);
        };
        self.tokens.insert(
            name.clone(),
            Token {
                value,
                description: format!("The provider's {var}, read by the Kubernetes manifests"),
                owner,
            },
        );
        Ok(Some(format!("${{{name}}}")))
    }

    fn collision(&self, name: &str) -> GenError {
        GenError::Emit(format!(
            "two Kubernetes values would share the output name {name}; rename one of the resources"
        ))
    }

    fn step(&mut self, w: &EntityRef, title: &str, body: String) {
        self.manual.push(ManualEntry {
            entity: Some(w.id.to_string()),
            title: format!("{} \"{}\": {title}", self.display(w), w.name),
            body,
        });
    }

    /// Every object for one workload, plus what the README says about it.
    fn workload(&mut self, w: &EntityRef<'a>) -> Result<(Vec<J>, Summary), GenError> {
        let p = self.p;
        let name = k8s_name(w.name);
        let ns = str_field(w, "namespace").unwrap_or("default".into());
        let sa = str_field(w, "service_account").unwrap_or(name.clone());
        let labels = json!({
            "app.kubernetes.io/name": name,
            "app.kubernetes.io/managed-by": "terratofu-gui",
        });
        let meta = |obj_name: &str| json!({ "name": obj_name, "namespace": ns, "labels": labels });
        let mut docs = Vec::new();
        let mut objects = Vec::new();

        // ------------------------------------------------ ServiceAccount
        // Named exactly as the identity binding says: the pod identity association (AWS),
        // the federated credential's subject (Azure), the workloadIdentityUser member (GCP).
        let mut sa_meta = meta(&sa);
        let role = relation_targets_of_type(p, self.cat, w, Relation::IamBinding, None)
            .into_iter()
            .next();
        let annotation = match self.provider {
            "azure" => Some(("azure.workload.identity/client-id", "CLIENT_ID")),
            "gcp" => Some(("iam.gke.io/gcp-service-account", "EMAIL")),
            _ => None,
        };
        if let (Some((key, conn)), Some(role)) = (annotation, &role) {
            if let Some(tok) = self.token(role, conn)? {
                sa_meta["annotations"] = json!({ key: tok });
            }
        }
        docs.push(json!({ "apiVersion": "v1", "kind": "ServiceAccount", "metadata": sa_meta }));
        objects.push(format!("ServiceAccount {sa}"));

        // ------------------------------------------------ environment
        let mut env = Vec::new();
        let mut seen = HashSet::new();
        let edges: Vec<ttg_core::Edge> = p.edges_from(w.id).cloned().collect();
        for edge in edges {
            if !matches!(
                edge.relation,
                Relation::AttributeReference | Relation::SendsTo | Relation::Reads | Relation::LogsTo
            ) {
                continue;
            }
            let Some(t) = p.entity(&edge.target) else {
                continue;
            };
            if diagnostics::manifests_only(self.cat, w.resource_type, edge.relation, t.resource_type)
                || !seen.insert(t.id.to_string())
            {
                continue;
            }
            let Some(m) = self.cat.mapping(t.resource_type, self.provider) else {
                continue;
            };
            let prefix = self
                .cat
                .resource(t.resource_type)
                .map(|d| d.resource.env_prefix())
                .unwrap_or_default();
            let keys: Vec<String> = m.connection.keys().cloned().collect();
            for key in keys {
                if let Some(tok) = self.token(t.id, &key)? {
                    env.push(EnvRow {
                        name: format!("{prefix}_{}_{key}", env_part(t.name)),
                        value: tok,
                        from: format!("{} \"{}\"", self.display(&t), t.name),
                    });
                }
            }
        }
        env.sort_by(|a, b| a.name.cmp(&b.name));

        // ------------------------------------------------ image
        let image = self.image(w, &name)?;

        // ------------------------------------------------ scheduling
        let mut node_selector = Map::new();
        let mut tolerations = Vec::new();
        let pools = self.targets(w, Relation::Attachment, "kubernetes_node_pool");
        if let Some(pool) = pools.first().and_then(|id| p.entity(id)) {
            let labels = pool.field("labels").and_then(|v| v.as_list()).unwrap_or(&[]);
            for entry in labels {
                let (k, v) = entry.split_once('=').unwrap_or((entry.as_str(), ""));
                node_selector.insert(k.trim().to_string(), J::String(v.trim().to_string()));
            }
            if node_selector.is_empty() {
                // No labels of its own: select the pool by the label every provider puts
                // on a pool's nodes, named the way the node pool mapping names the pool.
                let (key, value) = match self.provider {
                    "azure" => (
                        "kubernetes.azure.com/agentpool",
                        pool.provider_field("azure", "pool_name")
                            .filter(|v| !v.is_empty())
                            .map(|v| v.display())
                            .unwrap_or_else(|| Transform::Alnum.apply(pool.name)),
                    ),
                    "gcp" => ("cloud.google.com/gke-nodepool", k8s_name(pool.name)),
                    _ => ("eks.amazonaws.com/nodegroup", k8s_name(pool.name)),
                };
                node_selector.insert(key.into(), J::String(value));
            }
            for row in pool.field("taints").and_then(|v| v.as_records()).unwrap_or(&[]) {
                let get = |k: &str| row.get(k).map(|v| v.display()).unwrap_or_default();
                tolerations.push(json!({
                    "key": get("key"),
                    "operator": "Equal",
                    "value": get("value"),
                    "effect": get("effect"),
                }));
            }
            // AKS taints its spot pools itself (the node pool definition says so).
            if self.provider == "azure" && pool.field("spot").and_then(|v| v.as_bool()) == Some(true) {
                tolerations.push(json!({
                    "key": "kubernetes.azure.com/scalesetpriority",
                    "operator": "Equal",
                    "value": "spot",
                    "effect": "NoSchedule",
                }));
            }
        }

        // ------------------------------------------------ resources
        let cpu = str_field(w, "cpu");
        let memory = str_field(w, "memory");
        let gpu = self.int_field(w, "gpu").unwrap_or(0);
        let mut requests = Map::new();
        let mut limits = Map::new();
        if let Some(c) = &cpu {
            requests.insert("cpu".into(), J::String(c.clone()));
        }
        if let Some(m) = &memory {
            // A memory limit equal to the request keeps the pod out of the node's way
            // when it grows; CPU is left unlimited so it may burst.
            requests.insert("memory".into(), J::String(m.clone()));
            limits.insert("memory".into(), J::String(m.clone()));
        }
        if gpu > 0 {
            requests.insert("nvidia.com/gpu".into(), J::String(gpu.to_string()));
            limits.insert("nvidia.com/gpu".into(), J::String(gpu.to_string()));
            if pools.is_empty() {
                self.notes.push(format!(
                    "`{name}` requests {gpu} GPU(s) but is not linked to a node pool ('Schedules on'); it will only start where the cluster's own nodes have GPUs."
                ));
            }
        }

        // ------------------------------------------------ port and load balancers
        let lbs: Vec<Id> = self.targets(w, Relation::Attachment, "load_balancer");
        let port = self.int_field(w, "port").or_else(|| {
            lbs.iter()
                .filter_map(|id| p.entity(id))
                .find_map(|lb| self.int_field(&lb, "target_port"))
        });

        // ------------------------------------------------ volumes
        let mut volumes = Vec::new();
        let mut mounts = Vec::new();
        for fs_id in self.targets(w, Relation::Attachment, "file_system") {
            let Some(fs) = p.entity(&fs_id) else { continue };
            let fs_name = k8s_name(fs.name);
            let claim = format!("{name}-{fs_name}");
            let pv = format!("{ns}-{claim}");
            let Some(csi) = self.csi(&fs_id, &pv)? else {
                self.notes.push(format!(
                    "`{name}` mounts \"{}\", but its {} mapping hands the manifests nothing to mount it with; no volume was generated.",
                    fs.name, self.provider
                ));
                continue;
            };
            let size = format!("{}Gi", self.int_field(&fs, "size_gb").unwrap_or(100));
            let mut pv_spec = json!({
                "capacity": { "storage": size },
                "accessModes": ["ReadWriteMany"],
                "persistentVolumeReclaimPolicy": "Retain",
                "storageClassName": "",
                "claimRef": { "namespace": ns, "name": claim },
                "csi": csi,
            });
            if self.provider == "azure" {
                pv_spec["mountOptions"] = json!(["vers=4", "minorversion=1", "sec=sys"]);
            }
            // Static provisioning: the volume names its claim and the claim its volume,
            // so neither needs a StorageClass and they cannot bind to anything else.
            docs.push(json!({
                "apiVersion": "v1",
                "kind": "PersistentVolume",
                "metadata": { "name": pv, "labels": labels },
                "spec": pv_spec,
            }));
            docs.push(json!({
                "apiVersion": "v1",
                "kind": "PersistentVolumeClaim",
                "metadata": meta(&claim),
                "spec": {
                    "accessModes": ["ReadWriteMany"],
                    "storageClassName": "",
                    "volumeName": pv,
                    "resources": { "requests": { "storage": size } },
                },
            }));
            objects.push(format!("PersistentVolume {pv}"));
            objects.push(format!("PersistentVolumeClaim {claim}"));
            volumes.push(json!({ "name": fs_name, "persistentVolumeClaim": { "claimName": claim } }));
            mounts.push(json!({ "name": fs_name, "mountPath": format!("/mnt/{fs_name}") }));
        }

        // ------------------------------------------------ Deployment
        let mut container = Map::new();
        container.insert("name".into(), J::String(name.clone()));
        container.insert("image".into(), J::String(image.clone()));
        if let Some(port) = port {
            container.insert(
                "ports".into(),
                json!([{ "name": "app", "containerPort": port, "protocol": "TCP" }]),
            );
        }
        if !env.is_empty() {
            container.insert(
                "env".into(),
                J::Array(
                    env.iter()
                        .map(|r| json!({ "name": r.name, "value": r.value }))
                        .collect(),
                ),
            );
        }
        let mut resources = Map::new();
        if !requests.is_empty() {
            resources.insert("requests".into(), J::Object(requests));
        }
        if !limits.is_empty() {
            resources.insert("limits".into(), J::Object(limits));
        }
        if !resources.is_empty() {
            container.insert("resources".into(), J::Object(resources));
        }
        if !mounts.is_empty() {
            container.insert("volumeMounts".into(), J::Array(mounts));
        }
        let mut pod_spec = Map::new();
        pod_spec.insert("serviceAccountName".into(), J::String(sa.clone()));
        if !node_selector.is_empty() {
            pod_spec.insert("nodeSelector".into(), J::Object(node_selector));
        }
        if !tolerations.is_empty() {
            pod_spec.insert("tolerations".into(), J::Array(tolerations));
        }
        pod_spec.insert("containers".into(), json!([J::Object(container)]));
        if !volumes.is_empty() {
            pod_spec.insert("volumes".into(), J::Array(volumes));
        }
        let mut pod_labels = labels.clone();
        if self.provider == "azure" {
            // Workload identity only injects a token into pods that ask for one.
            pod_labels["azure.workload.identity/use"] = json!("true");
        }

        let autoscale = self.autoscaling(w, &name, &ns, &labels, &cpu)?;
        let mut spec = Map::new();
        if autoscale.is_empty() {
            spec.insert(
                "replicas".into(),
                json!(self.int_field(w, "replicas").unwrap_or(1).max(0)),
            );
        }
        spec.insert(
            "selector".into(),
            json!({ "matchLabels": { "app.kubernetes.io/name": name } }),
        );
        spec.insert(
            "template".into(),
            json!({ "metadata": { "labels": pod_labels }, "spec": J::Object(pod_spec) }),
        );
        docs.push(json!({
            "apiVersion": "apps/v1",
            "kind": "Deployment",
            "metadata": meta(&name),
            "spec": J::Object(spec),
        }));
        objects.push(format!("Deployment {name}"));

        // ------------------------------------------------ Service and bindings
        if let Some(port) = port {
            let mut svc_meta = meta(&name);
            if self.provider == "gcp" && !lbs.is_empty() {
                // GKE creates a network endpoint group for the port, which is what the
                // load balancer's backend service takes (its own manual step says how).
                svc_meta["annotations"] = json!({
                    "cloud.google.com/neg": format!("{{\"exposed_ports\":{{\"{port}\":{{}}}}}}"),
                });
            }
            docs.push(json!({
                "apiVersion": "v1",
                "kind": "Service",
                "metadata": svc_meta,
                "spec": {
                    "type": "ClusterIP",
                    "selector": { "app.kubernetes.io/name": name },
                    "ports": [{ "name": "app", "port": port, "targetPort": port, "protocol": "TCP" }],
                },
            }));
            objects.push(format!("Service {name}"));
        }
        for lb_id in &lbs {
            let Some(lb) = p.entity(lb_id) else { continue };
            let forwards = !self
                .targets(&lb, Relation::Attachment, "kubernetes_cluster")
                .is_empty();
            match self.provider {
                "aws" if !forwards => self.notes.push(format!(
                    "`{name}` receives traffic from \"{}\", which does not forward to a Kubernetes cluster, so its target group registers instances and no TargetGroupBinding was generated. Link the load balancer's 'Forwards to' to the cluster.",
                    lb.name
                )),
                "aws" => {
                    let Some(port) = port else {
                        self.notes.push(format!(
                            "`{name}` receives traffic from \"{}\" but has no port, so there is no Service to bind its target group to. Set the workload's **Port**.",
                            lb.name
                        ));
                        continue;
                    };
                    let Some(arn) = self.token(lb_id, "TARGET_GROUP_ARN")? else {
                        continue;
                    };
                    let tgb = if lbs.len() == 1 {
                        name.clone()
                    } else {
                        format!("{name}-{}", k8s_name(lb.name))
                    };
                    docs.push(json!({
                        "apiVersion": "elbv2.k8s.aws/v1beta1",
                        "kind": "TargetGroupBinding",
                        "metadata": meta(&tgb),
                        "spec": {
                            "serviceRef": { "name": name, "port": port },
                            "targetGroupARN": arn,
                            "targetType": "ip",
                        },
                    }));
                    objects.push(format!("TargetGroupBinding {tgb}"));
                    self.lb_controller = true;
                }
                "azure" => self.notes.push(format!(
                    "`{name}` receives traffic from \"{}\". An Azure Load Balancer cannot target pods: publish the Service with `type: LoadBalancer` (AKS then runs its own load balancer) or put an Application Gateway with the AGIC add-on, or the Gateway API, in front of it. No controller-specific objects are generated.",
                    lb.name
                )),
                _ => self.notes.push(format!(
                    "`{name}` receives traffic from \"{}\": its Service carries the `cloud.google.com/neg` annotation, so GKE creates a network endpoint group for port {}. Add that NEG as a backend of the load balancer's backend service.",
                    lb.name,
                    port.map(|p| p.to_string()).unwrap_or("?".into())
                )),
            }
        }
        docs.extend(autoscale.iter().cloned());
        for d in &autoscale {
            objects.push(format!(
                "{} {}",
                d["kind"].as_str().unwrap_or(""),
                d["metadata"]["name"].as_str().unwrap_or("")
            ));
        }

        Ok((
            docs,
            Summary {
                name: name.clone(),
                namespace: ns,
                file: format!("{name}.yaml"),
                image,
                env,
                objects,
            },
        ))
    }

    /// The container image: `<registry>/<repository>:<tag>` from a linked Container
    /// Registry, else the workload's own **Image**, else a placeholder. Anything the
    /// operator still has to decide becomes a manual step.
    fn image(&mut self, w: &EntityRef<'a>, name: &str) -> Result<String, GenError> {
        let tag_or_placeholder = str_field(w, "image_tag").unwrap_or(IMAGE_TAG_PLACEHOLDER.into());
        let registry = self
            .targets(w, Relation::Attachment, "container_registry")
            .into_iter()
            .next();
        let image = if let Some(reg_id) = registry {
            let reg = self.p.entity(&reg_id).expect("linked registry exists");
            let listed: Vec<String> = reg
                .field("repositories")
                .and_then(|v| v.as_list())
                .map(|l| l.to_vec())
                .unwrap_or_default();
            let wanted = str_field(w, "repository");
            // The workload's repository, else the registry's only one, else the registry
            // itself (on AWS a registry with no list *is* its one repository).
            let repo = match (&wanted, listed.as_slice()) {
                (Some(r), _) => r.clone(),
                (None, [only]) => only.clone(),
                (None, _) => reg.name.to_string(),
            };
            if !listed.is_empty() && !listed.iter().any(|r| k8s_name(r) == k8s_name(&repo)) {
                let body = if wanted.is_some() {
                    format!(
                        "The workload pulls `{repo}`, which is not one of the repositories \"{}\" lists ({}). Pick one of them in the workload's **Repository**, or add it to the registry.",
                        reg.name,
                        listed.join(", ")
                    )
                } else {
                    format!(
                        "\"{}\" lists several repositories ({}), so the workload's **Repository** must say which one it runs; the Deployment uses `{repo}` until it does.",
                        reg.name,
                        listed.join(", ")
                    )
                };
                self.step(w, "choose the image repository", body);
            }
            match self.token(&reg_id, "REGISTRY")? {
                Some(host) => format!("{host}/{}:{tag_or_placeholder}", k8s_name(&repo)),
                None => format!("{}:{tag_or_placeholder}", k8s_name(&repo)),
            }
        } else if let Some(img) = str_field(w, "image") {
            let last = img.rsplit('/').next().unwrap_or(&img);
            if last.contains(':') || img.contains('@') {
                img
            } else {
                format!("{img}:{tag_or_placeholder}")
            }
        } else {
            self.step(
                w,
                "name the container image",
                format!(
                    "The Deployment in `k8s/{name}.yaml` runs the placeholder image `registry.invalid/{name}`. Link the workload to a Container Registry ('Runs image from') or set its **Image**, then export again."
                ),
            );
            format!("registry.invalid/{name}:{tag_or_placeholder}")
        };
        // A full **Image** reference may carry its own tag; only the placeholder needs one.
        if image.ends_with(&format!(":{IMAGE_TAG_PLACEHOLDER}")) {
            self.step(
                w,
                "set the image tag",
                format!(
                    "The Deployment in `k8s/{name}.yaml` runs the tag `{IMAGE_TAG_PLACEHOLDER}`, which no registry has, so the pods will not start. Set the workload's **Image tag** to the tag your pipeline pushes and export again (or set the image with `kubectl set image` after applying)."
                ),
            );
        }
        Ok(image)
    }

    /// The CSI source of a static PersistentVolume for a linked file system.
    fn csi(&mut self, fs: &str, pv: &str) -> Result<Option<J>, GenError> {
        Ok(match self.provider {
            "aws" => self
                .token(fs, "ID")?
                .map(|id| json!({ "driver": "efs.csi.aws.com", "volumeHandle": id })),
            "azure" => {
                let (Some(rg), Some(account), Some(share)) = (
                    self.token(fs, "RESOURCE_GROUP")?,
                    self.token(fs, "ACCOUNT")?,
                    self.token(fs, "SHARE")?,
                ) else {
                    return Ok(None);
                };
                Some(json!({
                    "driver": "file.csi.azure.com",
                    // Unique per volume across the cluster, as the driver requires.
                    "volumeHandle": format!("{rg}#{account}#{share}#{pv}"),
                    "volumeAttributes": {
                        "resourceGroup": rg,
                        "storageAccount": account,
                        "shareName": share,
                        "protocol": "nfs",
                    },
                }))
            }
            _ => {
                let (Some(handle), Some(ip)) = (self.token(fs, "VOLUME_HANDLE")?, self.token(fs, "IP")?)
                else {
                    return Ok(None);
                };
                Some(json!({
                    "driver": "filestore.csi.storage.gke.io",
                    "volumeHandle": handle,
                    "volumeAttributes": { "ip": ip, "volume": "share" },
                }))
            }
        })
    }

    /// A KEDA ScaledObject (and its TriggerAuthentication) for a workload that consumes
    /// queues, or a CPU HorizontalPodAutoscaler for one that does not. Only when
    /// **Max replicas** is set; empty otherwise, and the Deployment keeps its replicas.
    fn autoscaling(
        &mut self,
        w: &EntityRef<'a>,
        name: &str,
        ns: &str,
        labels: &J,
        cpu: &Option<String>,
    ) -> Result<Vec<J>, GenError> {
        let Some(max) = w.field("max_replicas").and_then(|v| v.as_int()) else {
            return Ok(Vec::new());
        };
        let min = self.int_field(w, "min_replicas").unwrap_or(1).max(0);
        let max = if max < min.max(1) {
            self.notes.push(format!(
                "`{name}`: Max replicas ({max}) is below Min replicas ({min}); the autoscaler uses {} for both.",
                min.max(1)
            ));
            min.max(1)
        } else {
            max
        };
        let meta = |n: &str| json!({ "name": n, "namespace": ns, "labels": labels });
        let queues = self.targets(w, Relation::AttributeReference, "event_queue");
        if queues.is_empty() {
            if cpu.is_none() {
                self.notes.push(format!(
                    "`{name}` has Max replicas but no CPU request, which a CPU autoscaler needs, and consumes no queue KEDA could scale on; no autoscaler was generated."
                ));
                return Ok(Vec::new());
            }
            if min == 0 {
                self.notes.push(format!(
                    "`{name}`: a HorizontalPodAutoscaler cannot scale to zero, so it keeps at least one replica."
                ));
            }
            return Ok(vec![json!({
                "apiVersion": "autoscaling/v2",
                "kind": "HorizontalPodAutoscaler",
                "metadata": meta(name),
                "spec": {
                    "scaleTargetRef": { "apiVersion": "apps/v1", "kind": "Deployment", "name": name },
                    "minReplicas": min.max(1),
                    "maxReplicas": max,
                    "metrics": [{
                        "type": "Resource",
                        "resource": { "name": "cpu", "target": { "type": "Utilization", "averageUtilization": 70 } },
                    }],
                },
            })]);
        }
        let per_replica = self
            .int_field(w, "messages_per_replica")
            .unwrap_or(5)
            .max(1)
            .to_string();
        let auth = format!("{name}-keda");
        let mut triggers = Vec::new();
        for q in &queues {
            let metadata = match self.provider {
                "aws" => {
                    let (Some(url), Some(region)) = (self.token(q, "URL")?, self.var_token("region")?) else {
                        continue;
                    };
                    json!({ "queueURL": url, "queueLength": per_replica, "awsRegion": region })
                }
                "azure" => {
                    let (Some(queue), Some(namespace)) =
                        (self.token(q, "NAME")?, self.token(q, "NAMESPACE")?)
                    else {
                        continue;
                    };
                    json!({ "queueName": queue, "namespace": namespace, "messageCount": per_replica })
                }
                _ => {
                    let Some(sub) = self.token(q, "SUBSCRIPTION")? else {
                        continue;
                    };
                    json!({ "subscriptionName": sub, "mode": "SubscriptionSize", "value": per_replica })
                }
            };
            let kind = match self.provider {
                "aws" => "aws-sqs-queue",
                "azure" => "azure-servicebus",
                _ => "gcp-pubsub",
            };
            triggers
                .push(json!({ "type": kind, "authenticationRef": { "name": auth }, "metadata": metadata }));
        }
        if triggers.is_empty() {
            return Ok(Vec::new());
        }
        self.keda = true;
        // KEDA reads the queue depth with its *own* identity (the operator's), never the
        // workload's: the workload's role stays exactly what its links grant.
        let identity = match self.provider {
            "aws" => "aws",
            "azure" => "azure-workload",
            _ => "gcp",
        };
        Ok(vec![
            json!({
                "apiVersion": "keda.sh/v1alpha1",
                "kind": "ScaledObject",
                "metadata": meta(name),
                "spec": {
                    "scaleTargetRef": { "name": name },
                    "minReplicaCount": min,
                    "maxReplicaCount": max,
                    "triggers": triggers,
                },
            }),
            json!({
                "apiVersion": "keda.sh/v1alpha1",
                "kind": "TriggerAuthentication",
                "metadata": meta(&auth),
                "spec": { "podIdentity": { "provider": identity } },
            }),
        ])
    }

    /// The one manual step the manifests add: the controllers their custom resources need.
    fn controllers_step(&self) -> (String, String) {
        let mut parts = Vec::new();
        let mut body = String::from(
            "The manifests in `k8s/` use custom resources that only exist once their controller is installed in the cluster. Install these before `kubectl apply -f k8s/rendered/`:\n",
        );
        if self.keda {
            parts.push("KEDA");
            let identity = match self.provider {
                "aws" => "Give the operator (`keda/keda-operator`) an EKS Pod Identity association with a role that may call `sqs:GetQueueAttributes` on the scaled queues; the `TriggerAuthentication` objects use `podIdentity.provider: aws`, which is the operator's own identity.",
                "azure" => "Install it with workload identity on (`podIdentity.azureWorkload.enabled=true` and the client id of an identity federated with `system:serviceaccount:keda:keda-operator`), and give that identity **Azure Service Bus Data Owner** on the scaled queues' namespaces — KEDA reads the queue's runtime properties, which the receiver role does not cover.",
                _ => "Bind the operator's Kubernetes service account (`keda/keda-operator`) to a Google service account with `roles/monitoring.viewer`, and annotate it `iam.gke.io/gcp-service-account`; the `TriggerAuthentication` objects use `podIdentity.provider: gcp`.",
            };
            body.push_str(&format!(
                "\n* **KEDA** 2.13 or later (`helm install keda kedacore/keda -n keda --create-namespace`), for the `ScaledObject` / `TriggerAuthentication` objects. {identity}\n"
            ));
        }
        if self.lb_controller {
            parts.push("the AWS Load Balancer Controller");
            body.push_str(
                "\n* **AWS Load Balancer Controller** (`helm install aws-load-balancer-controller eks/aws-load-balancer-controller -n kube-system --set clusterName=<cluster>`), for the `TargetGroupBinding` objects that register the pods with the load balancer's target group. It needs an IAM role with the controller's published policy, bound to `kube-system/aws-load-balancer-controller`.\n",
            );
        }
        (
            format!("Kubernetes manifests: install {}", parts.join(" and ")),
            body,
        )
    }

    fn readme(
        &self,
        provider_display: &str,
        profile: Profile,
        workloads: &[Summary],
        files: &[(String, String)],
    ) -> String {
        let bin = profile.binary();
        let mut s = format!(
            "# Kubernetes manifests — {} ({provider_display})\n\n\
             Generated by TerraTofu GUI beside the {} configuration in the parent directory: \
             one file per Kubernetes Workload in the diagram, plus the namespaces they use.\n\n\
             ## Apply\n\n\
             ```\n{bin} apply                      # in the parent directory\n\
             ./k8s/render.sh                 # or: pwsh ./k8s/render.ps1\n\
             kubectl apply -f k8s/rendered/\n```\n\n\
             Values Terraform only knows after `apply` (queue URLs, file system ids, the target \
             group ARN, the registry address) appear in these files as `${{k8s_...}}` tokens, one per \
             output of the same name in `outputs.tf`. The render scripts read each output with \
             `{bin} output` and write the finished manifests to `k8s/rendered/`, which is \
             the directory to apply. Set `TF=terraform` (or `-Tool terraform`) to render with the \
             other binary, and `TF_DIR` (`-Dir`) when the configuration is not in the parent \
             directory. A token that has no output is an error, never an empty value.\n\n\
             Generating these as `kubernetes_manifest` / `helm_release` resources through the \
             Terraform `kubernetes` and `helm` providers instead is future work: those providers \
             need the cluster's API (and its CRDs) to exist when they plan, which the same apply \
             is only about to create, and they put the manifests in the state. The render step \
             keeps the two stages apart.\n",
            self.p.name,
            profile.display_name(),
        );
        s.push_str("\n## Files\n\n");
        for (path, _) in files {
            let f = path.trim_start_matches(&format!("{DIR}/"));
            if let Some(w) = workloads.iter().find(|w| w.file == f) {
                s.push_str(&format!(
                    "- `{f}` — {} (namespace `{}`)\n",
                    w.objects.join(", "),
                    w.namespace
                ));
            } else if f == "00-namespaces.yaml" {
                s.push_str(&format!("- `{f}` — the namespaces, applied first\n"));
            }
        }
        s.push_str("- `render.sh`, `render.ps1` — fill in the tokens into `rendered/`\n");

        s.push_str("\n## Before you apply\n\n");
        let prereqs: &[&str] = match self.provider {
            "aws" => &[
                "The cluster's **Add-ons** include `pod_identity_agent` (the ServiceAccounts carry no annotation: EKS Pod Identity binds them by name) and, for mounted file systems, `efs_csi`.",
            ],
            "azure" => &[
                "The cluster has the OIDC issuer and workload identity on (TerraTofu switches both on); pods carry the `azure.workload.identity/use` label and the ServiceAccounts the identity's client id.",
                "Mounted file systems use the built-in Azure Files CSI driver over NFS, which needs a private route to the storage account (see the File System's manual step).",
            ],
            _ => &[
                "The cluster has Workload Identity on (TerraTofu sets the workload pool); the ServiceAccounts carry the `iam.gke.io/gcp-service-account` annotation.",
                "Mounted file systems need the Filestore CSI driver (`addons_config.gcp_filestore_csi_driver_config`).",
            ],
        };
        for line in prereqs {
            s.push_str(&format!("- {line}\n"));
        }
        if self.keda {
            s.push_str("- **KEDA** for the `ScaledObject`s (see MANUAL_STEPS.md for its identity).\n");
        }
        if self.lb_controller {
            s.push_str("- The **AWS Load Balancer Controller** for the `TargetGroupBinding`s.\n");
        }

        s.push_str(
            "\n## Environment variables\n\n\
             Each resource a workload uses, sends to, reads or logs to becomes one variable per \
             value its definition exports, named `<PREFIX>_<RESOURCE NAME>_<KEY>` — `QUEUE_JOBS_URL`, \
             `BUCKET_TRANSCRIPTS_NAME`, `SECRET_API_KEY_ARN`, `DB_CORE_DB_HOST`. The prefix is the \
             resource type's (`QUEUE`, `TOPIC`, `BUCKET`, `SECRET`, `DB`, `CACHE`, `LOG_GROUP`), the \
             name is the display name in upper snake case and the keys differ per provider.\n",
        );
        for w in workloads {
            s.push_str(&format!("\n### {}\n\nImage: `{}`\n\n", w.name, w.image));
            if w.env.is_empty() {
                s.push_str("No environment variables.\n");
                continue;
            }
            s.push_str("| Variable | Value | From |\n|---|---|---|\n");
            for r in &w.env {
                s.push_str(&format!("| `{}` | `{}` | {} |\n", r.name, r.value, r.from));
            }
        }
        if !self.notes.is_empty() {
            s.push_str("\n## Notes\n\n");
            for n in &self.notes {
                s.push_str(&format!("- {n}\n"));
            }
        }
        s
    }
}

/// Join documents into one multi-document YAML file under a comment header.
fn render_docs(header: &str, docs: &[J]) -> String {
    let mut out = String::from(header);
    for d in docs {
        out.push_str("---\n");
        out.push_str(&to_yaml(d));
    }
    out
}

/// `render.sh`: bash 3.2 or later (macOS's), no jq and no envsubst — each token is read
/// with `<tool> output -raw` and substituted with bash's own string replacement.
fn render_sh(tokens: &[String], profile: Profile) -> String {
    let mut s = format!(
        "#!/usr/bin/env bash\n\
         # Generated by TerraTofu GUI. Copies the manifests next to this script into\n\
         # ./rendered/, replacing every ${{k8s_...}} token with the Terraform output of the\n\
         # same name. Run it after `{bin} apply`.\n\
         #\n\
         #   TF      the binary to read outputs with (default: {bin})\n\
         #   TF_DIR  the configuration directory (default: the parent of this one)\n\
         set -euo pipefail\n\
         shopt -u patsub_replacement 2>/dev/null || true\n\
         here=\"$(cd \"$(dirname \"$0\")\" && pwd)\"\n\
         tf=\"${{TF:-{bin}}}\"\n\
         root=\"${{TF_DIR:-$here/..}}\"\n\
         out=\"$here/rendered\"\n\
         names=(\n",
        bin = profile.binary()
    );
    for t in tokens {
        s.push_str(&format!("  {t}\n"));
    }
    s.push_str(
        ")\n\
         values=()\n\
         for n in ${names[@]+\"${names[@]}\"}; do\n\
         \x20 if ! v=\"$(\"$tf\" -chdir=\"$root\" output -raw \"$n\")\"; then\n\
         \x20   echo \"render.sh: no output '$n' in $root; run '$tf apply' first\" >&2\n\
         \x20   exit 1\n\
         \x20 fi\n\
         \x20 # The tokens sit inside double-quoted YAML strings.\n\
         \x20 v=${v//\\\\/\\\\\\\\}\n\
         \x20 v=${v//\\\"/\\\\\\\"}\n\
         \x20 values+=(\"$v\")\n\
         done\n\
         mkdir -p \"$out\"\n\
         count=0\n\
         for f in \"$here\"/*.yaml; do\n\
         \x20 [ -e \"$f\" ] || continue\n\
         \x20 content=\"$(cat \"$f\"; printf x)\"\n\
         \x20 content=${content%x}\n\
         \x20 i=0\n\
         \x20 for n in ${names[@]+\"${names[@]}\"}; do\n\
         \x20   pattern=\"\\${$n}\"\n\
         \x20   content=${content//\"$pattern\"/${values[$i]}}\n\
         \x20   i=$((i + 1))\n\
         \x20 done\n\
         \x20 printf '%s' \"$content\" > \"$out/$(basename \"$f\")\"\n\
         \x20 count=$((count + 1))\n\
         done\n\
         echo \"rendered $count file(s) into $out; apply them with: kubectl apply -f $out\"\n",
    );
    s
}

/// `render.ps1`: Windows PowerShell 5.1 or PowerShell 7; `<tool> output -json` is parsed
/// natively.
fn render_ps1(tokens: &[String], profile: Profile) -> String {
    let mut s = format!(
        "# Generated by TerraTofu GUI. Copies the manifests next to this script into\n\
         # .\\rendered\\, replacing every ${{k8s_...}} token with the Terraform output of the\n\
         # same name. Run it after `{bin} apply`.\n\
         param(\n\
         \x20   [string]$Tool = \"{bin}\",\n\
         \x20   [string]$Dir = (Join-Path $PSScriptRoot \"..\")\n\
         )\n\
         $ErrorActionPreference = \"Stop\"\n\
         $names = @(\n",
        bin = profile.binary()
    );
    let quoted: Vec<String> = tokens.iter().map(|t| format!("    \"{t}\"")).collect();
    s.push_str(&quoted.join(",\n"));
    if !quoted.is_empty() {
        s.push('\n');
    }
    s.push_str(
        ")\n\
         $json = (& $Tool \"-chdir=$Dir\" output -json) | Out-String\n\
         if ($LASTEXITCODE -ne 0) { throw \"'$Tool output' failed in $Dir; run '$Tool apply' first\" }\n\
         $outputs = $json | ConvertFrom-Json\n\
         $values = @{}\n\
         foreach ($n in $names) {\n\
         \x20   $o = $outputs.PSObject.Properties[$n]\n\
         \x20   if ($null -eq $o) { throw \"render.ps1: no output '$n' in $Dir; run '$Tool apply' first\" }\n\
         \x20   # The tokens sit inside double-quoted YAML strings.\n\
         \x20   $values[$n] = ([string]$o.Value.value).Replace('\\', '\\\\').Replace('\"', '\\\"')\n\
         }\n\
         $out = Join-Path $PSScriptRoot \"rendered\"\n\
         New-Item -ItemType Directory -Force -Path $out | Out-Null\n\
         $count = 0\n\
         foreach ($f in Get-ChildItem -Path $PSScriptRoot -Filter *.yaml) {\n\
         \x20   $text = [System.IO.File]::ReadAllText($f.FullName)\n\
         \x20   foreach ($n in $names) { $text = $text.Replace('${' + $n + '}', $values[$n]) }\n\
         \x20   [System.IO.File]::WriteAllText((Join-Path $out $f.Name), $text)\n\
         \x20   $count++\n\
         }\n\
         Write-Output \"rendered $count file(s) into $out; apply them with: kubectl apply -f $out\"\n",
    );
    s
}

// ------------------------------------------------------------------ YAML

/// Render a JSON value as block-style YAML. Strings are written plain only when they
/// cannot be read back as anything else (no YAML 1.1 booleans, numbers, `${…}` tokens or
/// punctuation); everything else is a JSON-escaped double-quoted scalar, which YAML reads
/// as the same string. Maps keep their insertion order.
pub fn to_yaml(v: &J) -> String {
    let mut out = String::new();
    match v {
        J::Object(m) if !m.is_empty() => write_map(&mut out, m, 0),
        J::Array(a) if !a.is_empty() => write_list(&mut out, a, 0),
        other => {
            out.push_str(&scalar(other));
            out.push('\n');
        }
    }
    out
}

fn write_map(out: &mut String, m: &Map<String, J>, indent: usize) {
    let pad = " ".repeat(indent);
    for (k, v) in m {
        out.push_str(&format!("{pad}{}:", scalar_str(k)));
        write_value(out, v, indent);
    }
}

/// The part after `key:` — a scalar on the same line, or a nested block below it.
fn write_value(out: &mut String, v: &J, indent: usize) {
    match v {
        J::Object(inner) if !inner.is_empty() => {
            out.push('\n');
            write_map(out, inner, indent + 2);
        }
        J::Array(items) if !items.is_empty() => {
            out.push('\n');
            write_list(out, items, indent + 2);
        }
        other => {
            out.push(' ');
            out.push_str(&scalar(other));
            out.push('\n');
        }
    }
}

fn write_list(out: &mut String, items: &[J], indent: usize) {
    let pad = " ".repeat(indent);
    for item in items {
        match item {
            // A map item starts on the dash line: write it one level deeper, then swap
            // the first line's indentation for the dash.
            J::Object(m) if !m.is_empty() => {
                let mut block = String::new();
                write_map(&mut block, m, indent + 2);
                out.push_str(&pad);
                out.push_str("- ");
                out.push_str(&block[indent + 2..]);
            }
            J::Array(inner) if !inner.is_empty() => {
                out.push_str(&format!("{pad}-\n"));
                write_list(out, inner, indent + 2);
            }
            other => out.push_str(&format!("{pad}- {}\n", scalar(other))),
        }
    }
}

fn scalar(v: &J) -> String {
    match v {
        J::Null => "null".into(),
        J::Bool(b) => b.to_string(),
        J::Number(n) => n.to_string(),
        J::String(s) => scalar_str(s),
        J::Object(_) => "{}".into(),
        J::Array(_) => "[]".into(),
    }
}

fn scalar_str(s: &str) -> String {
    let plain = s.chars().next().is_some_and(|c| c.is_ascii_alphabetic())
        && s.chars()
            .all(|c| c.is_ascii_alphanumeric() || matches!(c, '-' | '_' | '.' | '/'))
        && !matches!(
            s.to_ascii_lowercase().as_str(),
            "y" | "n" | "yes" | "no" | "true" | "false" | "on" | "off" | "null"
        );
    if plain {
        s.to_string()
    } else {
        serde_json::to_string(s).expect("a string always serialises")
    }
}

/// Replace every `${name}` token in `text` with its value, escaped for the double-quoted
/// YAML string it sits in — what the render scripts do, for tests and previews.
pub fn render_tokens(text: &str, values: &IndexMap<String, String>) -> String {
    let mut out = text.to_string();
    for (name, value) in values {
        let escaped = value.replace('\\', "\\\\").replace('"', "\\\"");
        out = out.replace(&format!("${{{name}}}"), &escaped);
    }
    out
}

/// The `${…}` token names a manifest file contains, in order of first appearance. Only
/// output names count (letters, digits, `_`), so the header's `${k8s_...}` does not.
pub fn tokens_in(text: &str) -> Vec<String> {
    let mut out: Vec<String> = Vec::new();
    let mut rest = text;
    while let Some(i) = rest.find("${") {
        let after = &rest[i + 2..];
        let Some(end) = after.find('}') else { break };
        let name = &after[..end];
        let valid = !name.is_empty() && name.chars().all(|c| c.is_ascii_alphanumeric() || c == '_');
        if valid && !out.iter().any(|x| x == name) {
            out.push(name.to_string());
        }
        rest = &after[end + 1..];
    }
    out
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn yaml_quotes_what_would_read_back_differently() {
        let v = json!({
            "apiVersion": "v1",
            "kind": "ConfigMap",
            "metadata": { "name": "x", "labels": { "app.kubernetes.io/name": "x" } },
            "data": {
                "on": "yes",
                "port": "8080",
                "token": "${k8s_jobs_url}",
                "empty": "",
                "json": "{\"a\":1}",
            },
            "list": [ { "name": "a", "value": "b" }, "plain", 3, [ "nested" ] ],
            "none": [],
            "obj": {},
        });
        let y = to_yaml(&v);
        assert_eq!(
            y,
            "apiVersion: v1\nkind: ConfigMap\nmetadata:\n  name: x\n  labels:\n    app.kubernetes.io/name: x\n\
             data:\n  \"on\": \"yes\"\n  port: \"8080\"\n  token: \"${k8s_jobs_url}\"\n  empty: \"\"\n  json: \"{\\\"a\\\":1}\"\n\
             list:\n  - name: a\n    value: b\n  - plain\n  - 3\n  -\n    - nested\nnone: []\nobj: {}\n"
        );
    }

    #[test]
    fn tokens_are_found_and_rendered_escaped() {
        let text = "a: \"${k8s_a}\"\nb: \"${k8s_b}/x:${k8s_a}\"\n";
        assert_eq!(tokens_in(text), vec!["k8s_a", "k8s_b"]);
        let mut values = IndexMap::new();
        values.insert("k8s_a".to_string(), "q\"\\".to_string());
        values.insert("k8s_b".to_string(), "host".to_string());
        assert_eq!(
            render_tokens(text, &values),
            "a: \"q\\\"\\\\\"\nb: \"host/x:q\\\"\\\\\"\n"
        );
    }

    #[test]
    fn names() {
        assert_eq!(k8s_name("ASR Worker"), "asr-worker");
        assert_eq!(env_part("api key"), "API_KEY");
        assert_eq!(env_part("core db"), "CORE_DB");
    }
}
