//! Where the state lives and what protects it: the `backend` block, OpenTofu state
//! `encryption`, and the separate **bootstrap** root that creates the state store (and
//! the key that encrypts the state) before the main configuration can use them.
//!
//! Backend types are Terraform / OpenTofu concepts rather than provider mappings, so the
//! list of them and the keys each one takes live here, in code, next to the three
//! things that read it: settings validation (the app's settings panel and the MCP
//! `settings_set` tool), the `terraform {}` block the emitter writes into `versions.tf`,
//! and the design-time diagnostics.
//!
//! The bootstrap root is not hand-written HCL. It is a *small diagram of its own* — an
//! Object Storage node for the state bucket (inside a Resource Group on Azure) plus, when
//! one is chosen, the project's own Encryption Key — generated by the ordinary emitter
//! with the curated mappings. The bucket therefore gets exactly the posture a bucket drawn
//! on the canvas would get (versioning, public access blocked, TLS only), and the key
//! keeps the key policy its mapping writes, which the other resources encrypted with it
//! still rely on.

use crate::diagnostics::{Code, Diagnostic, Severity};
use hcl::{Block, Expression, Traversal, Variable};
use std::collections::BTreeMap;
use ttg_catalog::Catalog;
use ttg_core::{BackendConfig, Config, Container, Id, Node, Project, Tool, Value};

/// One backend type and the keys it takes.
#[derive(Debug)]
pub struct BackendKind {
    /// The backend's type label: `backend "<kind>" {}`.
    pub kind: &'static str,
    pub display: &'static str,
    /// `(key, help)` pairs that must be set.
    pub required: &'static [(&'static str, &'static str)],
    /// `(key, help)` pairs that may be set.
    pub optional: &'static [(&'static str, &'static str)],
    /// The catalog provider whose bootstrap root creates the store; `None` for `local`,
    /// which has nothing to create.
    pub provider: Option<&'static str>,
}

const KEY_PREFIX_HELP: &str =
    "Folder the state is kept under: <key_prefix>/terraform.tfstate. Defaults to the project name.";
const KEY_HELP: &str =
    "The whole state object key instead of key_prefix, e.g. team/app/terraform.tfstate. Leave empty to use key_prefix.";
const GCS_PREFIX_HELP: &str = "The backend's own name for key_prefix; set one or the other.";

/// Every backend type the settings accept, in the order the settings panel lists them.
pub const BACKENDS: &[BackendKind] = &[
    BackendKind {
        kind: "local",
        display: "Local file",
        required: &[],
        optional: &[("path", "State file path; defaults to terraform.tfstate next to the configuration.")],
        provider: None,
    },
    BackendKind {
        kind: "s3",
        display: "Amazon S3",
        required: &[
            ("bucket", "State bucket name (created by bootstrap/)."),
            ("region", "Region of the state bucket."),
        ],
        optional: &[
            ("key_prefix", KEY_PREFIX_HELP),
            ("key", KEY_HELP),
            (
                "kms_key_id",
                "KMS key ARN the S3 backend encrypts the state object with (SSE-KMS); empty = the bucket's default encryption.",
            ),
        ],
        provider: Some("aws"),
    },
    BackendKind {
        kind: "azurerm",
        display: "Azure Blob Storage",
        required: &[
            ("resource_group_name", "Resource group of the state storage account (created by bootstrap/)."),
            ("storage_account_name", "State storage account: 3-24 lowercase letters and digits, globally unique."),
            ("container_name", "Blob container the state is kept in."),
        ],
        optional: &[("key_prefix", KEY_PREFIX_HELP), ("key", KEY_HELP)],
        provider: Some("azure"),
    },
    BackendKind {
        kind: "gcs",
        display: "Google Cloud Storage",
        required: &[("bucket", "State bucket name (created by bootstrap/).")],
        optional: &[("key_prefix", KEY_PREFIX_HELP), ("prefix", GCS_PREFIX_HELP)],
        provider: Some("gcp"),
    },
];

pub fn backend_kind(kind: &str) -> Option<&'static BackendKind> {
    BACKENDS.iter().find(|b| b.kind == kind)
}

impl BackendKind {
    /// Every key this backend takes, required first.
    pub fn keys(&self) -> impl Iterator<Item = &'static str> + '_ {
        self.required.iter().chain(self.optional).map(|(k, _)| *k)
    }
    pub fn help(&self, key: &str) -> &'static str {
        self.required
            .iter()
            .chain(self.optional)
            .find(|(k, _)| *k == key)
            .map(|(_, h)| *h)
            .unwrap_or("")
    }
}

/// A copy with blank values dropped: an empty text box in the settings panel means "not
/// set", never "set to the empty string".
pub fn normalized(cfg: &BackendConfig) -> BackendConfig {
    BackendConfig {
        backend_type: cfg.backend_type.trim().to_string(),
        args: cfg
            .args
            .iter()
            .filter(|(_, v)| !v.trim().is_empty())
            .map(|(k, v)| (k.trim().to_string(), v.trim().to_string()))
            .collect(),
    }
}

/// Check a backend configuration: a known type, only that type's keys, every required
/// key set. The message names what is wrong and what would be right.
pub fn check_backend(cfg: &BackendConfig) -> Result<(), String> {
    let cfg = normalized(cfg);
    let Some(kind) = backend_kind(&cfg.backend_type) else {
        return Err(format!(
            "unknown backend type \"{}\"; use one of: {}",
            cfg.backend_type,
            BACKENDS.iter().map(|b| b.kind).collect::<Vec<_>>().join(", ")
        ));
    };
    let valid: Vec<&str> = kind.keys().collect();
    for k in cfg.args.keys() {
        if !valid.contains(&k.as_str()) {
            return Err(format!(
                "the {} backend takes {}; \"{k}\" is not one of them",
                kind.kind,
                valid.join(", ")
            ));
        }
    }
    for other in ["key", "prefix"] {
        if cfg.args.contains_key("key_prefix") && cfg.args.contains_key(other) {
            return Err(format!(
                "set key_prefix or {other}, not both: they say the same thing (the state object is <key_prefix>/terraform.tfstate)"
            ));
        }
    }
    let missing: Vec<&str> = kind
        .required
        .iter()
        .map(|(k, _)| *k)
        .filter(|k| !cfg.args.contains_key(*k))
        .collect();
    if !missing.is_empty() {
        return Err(format!(
            "the {} backend needs {}; missing: {}",
            kind.kind,
            kind.required
                .iter()
                .map(|(k, _)| *k)
                .collect::<Vec<_>>()
                .join(", "),
            missing.join(", ")
        ));
    }
    let prefix = ["key_prefix", "prefix", "key"]
        .iter()
        .find_map(|k| cfg.args.get(*k).map(|v| (*k, v)));
    if let Some((which, prefix)) = prefix {
        if prefix.starts_with('/')
            || prefix.ends_with('/')
            || prefix.split('/').any(|s| s.is_empty() || s == "." || s == "..")
            || prefix.chars().any(char::is_whitespace)
        {
            return Err(format!(
                "{which} \"{prefix}\" must be a relative path like `team/app`: no leading or trailing slash, no empty, `.` or `..` segments, no spaces"
            ));
        }
    }
    Ok(())
}

/// Read the `backend` argument of `settings_set`: `null` (or `{"type": "none"}`) clears
/// it; otherwise `{"type": "s3", "bucket": "…", "region": "…"}`, or the `{type, args}`
/// shape `project_get` returns. The result has passed [`check_backend`].
pub fn backend_from_json(v: &serde_json::Value) -> Result<Option<BackendConfig>, String> {
    use serde_json::Value as J;
    let obj = match v {
        J::Null => return Ok(None),
        J::Object(o) => o,
        _ => return Err("backend must be an object like {\"type\": \"s3\", \"bucket\": \"…\", \"region\": \"…\"}, or null".into()),
    };
    let kind = match obj.get("type") {
        Some(J::String(s)) => s.trim().to_string(),
        _ => {
            return Err(format!(
                "backend needs a \"type\": one of {}",
                BACKENDS.iter().map(|b| b.kind).collect::<Vec<_>>().join(", ")
            ))
        }
    };
    if kind == "none" {
        return Ok(None);
    }
    let text = |k: &str, v: &J| -> Result<String, String> {
        match v {
            J::String(s) => Ok(s.clone()),
            J::Number(n) => Ok(n.to_string()),
            _ => Err(format!("backend.{k} must be a string")),
        }
    };
    let mut args = BTreeMap::new();
    for (k, v) in obj {
        match k.as_str() {
            "type" => {}
            "args" => {
                let J::Object(inner) = v else {
                    return Err("backend.args must be an object".into());
                };
                for (ik, iv) in inner {
                    args.insert(ik.clone(), text(ik, iv)?);
                }
            }
            _ => {
                args.insert(k.clone(), text(k, v)?);
            }
        }
    }
    let cfg = normalized(&BackendConfig {
        backend_type: kind,
        args,
    });
    check_backend(&cfg)?;
    Ok(Some(cfg))
}

/// The folder the state is kept under: `<key_prefix>` (the `gcs` backend's own
/// `prefix` is accepted for it; default: the project name in kebab case), then the
/// environment when there is one. Named environments are a later package; every caller
/// passes `None` today, and the key already has room for one:
/// `<key_prefix>/<environment>/terraform.tfstate`.
pub fn state_prefix(p: &Project, cfg: &BackendConfig, environment: Option<&str>) -> String {
    let base = ["key_prefix", "prefix"]
        .iter()
        .find_map(|k| cfg.args.get(*k))
        .map(|s| s.trim().to_string())
        .filter(|s| !s.is_empty())
        .unwrap_or_else(|| kebab(&p.name));
    match env_segment(environment) {
        Some(env) => format!("{base}/{env}"),
        None => base,
    }
}

fn env_segment(environment: Option<&str>) -> Option<String> {
    environment.map(str::trim).filter(|e| !e.is_empty()).map(kebab)
}

/// The state object's key for the `s3` and `azurerm` backends:
/// `<key_prefix>[/<environment>]/terraform.tfstate`, or an explicit `key` with the
/// environment put in front of its file name.
pub fn state_key(p: &Project, cfg: &BackendConfig, environment: Option<&str>) -> String {
    if let Some(key) = cfg.args.get("key").map(|k| k.trim()).filter(|k| !k.is_empty()) {
        return match (env_segment(environment), key.rsplit_once('/')) {
            (None, _) => key.to_string(),
            (Some(env), Some((dir, file))) => format!("{dir}/{env}/{file}"),
            (Some(env), None) => format!("{env}/{key}"),
        };
    }
    format!("{}/terraform.tfstate", state_prefix(p, cfg, environment))
}

fn kebab(s: &str) -> String {
    ttg_core::slugify(s).replace('_', "-")
}

/// `backend "<type>" { … }`, every argument a literal: a backend block cannot use
/// variables (the backend is configured before anything is evaluated).
pub fn backend_block(p: &Project, cfg: &BackendConfig, environment: Option<&str>) -> Block {
    let cfg = normalized(cfg);
    let arg = |k: &str| cfg.args.get(k).cloned().unwrap_or_default();
    let b = Block::builder("backend").add_label(cfg.backend_type.as_str());
    let b = match cfg.backend_type.as_str() {
        "s3" => {
            let mut b = b
                .add_attribute(("bucket", arg("bucket")))
                .add_attribute(("key", state_key(p, &cfg, environment)))
                .add_attribute(("region", arg("region")))
                .add_attribute(("encrypt", true))
                // S3 conditional writes: no DynamoDB lock table (OpenTofu 1.10+, Terraform 1.11+).
                .add_attribute(("use_lockfile", true));
            if let Some(k) = cfg.args.get("kms_key_id") {
                b = b.add_attribute(("kms_key_id", k.as_str()));
            }
            b
        }
        "azurerm" => b
            .add_attribute(("resource_group_name", arg("resource_group_name")))
            .add_attribute(("storage_account_name", arg("storage_account_name")))
            .add_attribute(("container_name", arg("container_name")))
            .add_attribute(("key", state_key(p, &cfg, environment))),
        "gcs" => b
            .add_attribute(("bucket", arg("bucket")))
            .add_attribute(("prefix", state_prefix(p, &cfg, environment))),
        _ => {
            let mut b = b;
            if let Some(path) = cfg.args.get("path") {
                b = b.add_attribute(("path", path.as_str()));
            }
            b
        }
    };
    b.build()
}

/// The backend the export writes, if the settings hold a valid one.
pub fn configured_backend(p: &Project) -> Option<BackendConfig> {
    let cfg = normalized(p.settings.backend.as_ref()?);
    check_backend(&cfg).ok().map(|_| cfg)
}

/// A remote backend with a store for the bootstrap root to create (`local` has none).
fn remote_backend(p: &Project) -> Option<(BackendConfig, &'static BackendKind)> {
    let cfg = configured_backend(p)?;
    let kind = backend_kind(&cfg.backend_type)?;
    kind.provider.map(|_| (cfg, kind))
}

// ------------------------------------------------------------------ encryption

/// Which OpenTofu key provider protects the state.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum KeySource {
    /// `aws_kms`: an AWS KMS key generates the data keys.
    AwsKms,
    /// `gcp_kms`: a Cloud KMS crypto key wraps them.
    GcpKms,
    /// `pbkdf2`: a key derived from a passphrase variable (`state_passphrase`).
    Passphrase,
}

/// The effective state encryption for one provider's export.
#[derive(Debug, Clone)]
pub struct EncryptionPlan {
    pub source: KeySource,
    /// The `encryption_key` entity a KMS key provider uses.
    pub key: Option<Id>,
    /// The key is created by the bootstrap root (it is not flagged external).
    pub key_in_bootstrap: bool,
    /// AWS: the region the key lives in (the bootstrap root's region).
    pub region: Option<String>,
}

impl EncryptionPlan {
    /// The attribute of the key the key provider takes: its ARN on AWS, its full id
    /// (`projects/…/cryptoKeys/…`) on Google Cloud.
    pub fn key_attr(&self) -> Option<&'static str> {
        match self.source {
            KeySource::AwsKms => Some("arn"),
            KeySource::GcpKms => Some("id"),
            KeySource::Passphrase => None,
        }
    }
}

/// The entity `state_encryption_key` names, if it exists and is an Encryption Key.
pub fn state_key_entity(p: &Project) -> Option<Id> {
    let id = p.settings.state_encryption_key.as_deref()?;
    let e = p.entity(id)?;
    (e.resource_type == "encryption_key").then(|| e.id.to_string())
}

/// The AWS region the bootstrap root creates things in: the S3 backend's region when
/// the state is kept in S3 (the bucket must be there), else the project's AWS region.
pub fn aws_bootstrap_region(p: &Project, cat: &Catalog) -> String {
    if let Some(cfg) = configured_backend(p).filter(|c| c.backend_type == "s3") {
        if let Some(r) = cfg.args.get("region") {
            return r.clone();
        }
    }
    aws_region(p, cat)
}

fn aws_region(p: &Project, cat: &Catalog) -> String {
    p.settings
        .provider_settings
        .get("aws")
        .and_then(|m| m.get("region"))
        .filter(|s| !s.trim().is_empty())
        .cloned()
        .or_else(|| {
            cat.provider("aws")?
                .variables
                .iter()
                .find(|v| v.name == "region")?
                .default
                .as_ref()?
                .as_str()
                .map(str::to_string)
        })
        .unwrap_or_default()
}

/// The state encryption `layer` (one provider's layer of the project) gets, or `None`
/// when there is none: encryption off, or the tool is Terraform, which has no
/// `encryption` block.
pub fn encryption_plan(layer: &Project, cat: &Catalog, provider: &str, tool: Tool) -> Option<EncryptionPlan> {
    if !layer.settings.state_encryption || !crate::tool::Profile::new(tool).supports_state_encryption() {
        return None;
    }
    let key = state_key_entity(layer);
    let source = match (provider, &key) {
        ("aws", Some(_)) => KeySource::AwsKms,
        ("gcp", Some(_)) => KeySource::GcpKms,
        _ => KeySource::Passphrase,
    };
    if source == KeySource::Passphrase {
        return Some(EncryptionPlan {
            source,
            key: None,
            key_in_bootstrap: false,
            region: None,
        });
    }
    let key = key.unwrap();
    let manual = layer.entity(&key).is_some_and(|e| e.manual);
    Some(EncryptionPlan {
        source,
        key_in_bootstrap: !manual,
        region: (source == KeySource::AwsKms).then(|| aws_bootstrap_region(layer, cat)),
        key: Some(key),
    })
}

/// The name the key provider and method are declared under.
const ENC_NAME: &str = "state";

/// `encryption { key_provider … method … state { … } plan { … } }` (OpenTofu 1.7+).
/// `key` is the expression the KMS key provider takes (the key's ARN or id, a variable
/// in practice: the key lives in the bootstrap root).
pub fn encryption_block(plan: &EncryptionPlan, key: Option<Expression>) -> Block {
    let (kp_type, kp) = match plan.source {
        KeySource::AwsKms => (
            "aws_kms",
            Block::builder("key_provider")
                .add_label("aws_kms")
                .add_label(ENC_NAME)
                .add_attribute(("kms_key_id", key.unwrap_or(Expression::Null)))
                .add_attribute(("region", plan.region.clone().unwrap_or_default()))
                .add_attribute(("key_spec", "AES_256"))
                .build(),
        ),
        KeySource::GcpKms => (
            "gcp_kms",
            Block::builder("key_provider")
                .add_label("gcp_kms")
                .add_label(ENC_NAME)
                .add_attribute(("kms_encryption_key", key.unwrap_or(Expression::Null)))
                .add_attribute(("key_length", 32))
                .build(),
        ),
        KeySource::Passphrase => (
            "pbkdf2",
            Block::builder("key_provider")
                .add_label("pbkdf2")
                .add_label(ENC_NAME)
                .add_attribute(("passphrase", traversal(&["var", PASSPHRASE_VAR])))
                .build(),
        ),
    };
    let method = Block::builder("method")
        .add_label("aes_gcm")
        .add_label(ENC_NAME)
        .add_attribute(("keys", traversal(&["key_provider", kp_type, ENC_NAME])))
        .build();
    // `enforced`: refuse to read or write an unencrypted state or plan, so a missing
    // key fails loudly instead of silently writing plain text.
    let target = |name: &str| {
        Block::builder(name)
            .add_attribute(("method", traversal(&["method", "aes_gcm", ENC_NAME])))
            .add_attribute(("enforced", true))
            .build()
    };
    Block::builder("encryption")
        .add_block(kp)
        .add_block(method)
        .add_block(target("state"))
        .add_block(target("plan"))
        .build()
}

/// The variable a passphrase key provider reads.
pub const PASSPHRASE_VAR: &str = "state_passphrase";

fn traversal(parts: &[&str]) -> Expression {
    let mut t = Traversal::builder(Variable::unchecked(parts[0]));
    for p in &parts[1..] {
        t = t.attr(*p);
    }
    Expression::Traversal(Box::new(t.build()))
}

/// The lowest tool version the `terraform {}` block's state features need, if any is
/// above the profile's floor: S3 lock files (`use_lockfile`) arrived in OpenTofu 1.10
/// and Terraform 1.11, state encryption in OpenTofu 1.7.
pub fn required_version(p: &Project, tool: Tool, encrypted: bool) -> Option<&'static str> {
    let s3 = configured_backend(p).is_some_and(|c| c.backend_type == "s3");
    match tool {
        Tool::OpenTofu if s3 => Some(">= 1.10.0"),
        Tool::OpenTofu if encrypted => Some(">= 1.7.0"),
        Tool::Terraform if s3 => Some(">= 1.11.0"),
        _ => None,
    }
}

// ------------------------------------------------------------------ bootstrap

/// Directory (inside the export) of the bootstrap root.
pub const BOOTSTRAP_DIR: &str = "bootstrap";

/// Id of the state bucket in a bootstrap project.
pub const STORE_ID: &str = "tfstate-store";
const STORE_RG_ID: &str = "tfstate-rg";

/// One separate root the export writes under `bootstrap/`: a small project of its own
/// and the provider it is generated for.
#[derive(Debug, Clone)]
pub struct BootstrapRoot {
    /// Path inside the export: `bootstrap`, or `bootstrap/<provider>` for a second root
    /// when the state store and the state key are on different clouds.
    pub dir: String,
    pub provider: String,
    pub project: Project,
    /// The state key's id when this root creates it.
    pub key: Option<Id>,
    /// This root creates the backend's store.
    pub store: bool,
}

/// The bootstrap roots one provider's export gets: the remote backend's store, and the
/// state key when a KMS key provider uses one (the key must exist before the state it
/// encrypts, so it cannot be part of the configuration whose state that is). One root
/// when both are on the same cloud; two when they are not (an S3 backend for the Google
/// Cloud export encrypted with a Cloud KMS key). Empty when there is nothing to create.
pub fn bootstrap_roots(layer: &Project, cat: &Catalog, provider: &str, tool: Tool) -> Vec<BootstrapRoot> {
    let store = remote_backend(layer);
    let key = encryption_plan(layer, cat, provider, tool)
        .filter(|e| e.key_in_bootstrap)
        .and_then(|e| e.key);
    let mut roots: Vec<BootstrapRoot> = Vec::new();
    if let Some((cfg, kind)) = &store {
        let pid = kind.provider.unwrap();
        let mut mini = bootstrap_project(layer, pid, cat);
        add_store(&mut mini, layer, cfg, cat);
        roots.push(BootstrapRoot {
            dir: BOOTSTRAP_DIR.into(),
            provider: pid.into(),
            project: mini,
            key: None,
            store: true,
        });
    }
    if let Some(key) = key {
        match roots.iter_mut().find(|r| r.provider == provider) {
            Some(r) => {
                add_key(&mut r.project, layer, &key);
                r.key = Some(key);
            }
            None => {
                let mut mini = bootstrap_project(layer, provider, cat);
                add_key(&mut mini, layer, &key);
                let dir = if roots.is_empty() {
                    BOOTSTRAP_DIR.to_string()
                } else {
                    format!("{BOOTSTRAP_DIR}/{provider}")
                };
                roots.push(BootstrapRoot {
                    dir,
                    provider: provider.into(),
                    project: mini,
                    key: Some(key),
                    store: false,
                });
            }
        }
    }
    roots
}

/// An empty project with the main project's settings minus everything about state: the
/// bootstrap root keeps its own (small, secret-free) state locally.
fn bootstrap_project(main: &Project, provider: &str, cat: &Catalog) -> Project {
    let mut p = Project::new(&format!("{} state bootstrap", main.name));
    p.settings.tool = main.settings.tool;
    p.settings.target_provider = provider.to_string();
    p.settings.provider_settings = main.settings.provider_settings.clone();
    p.settings.tags = main.settings.tags.clone();
    p.settings.provider_versions = main.settings.provider_versions.clone();
    if provider == "aws" {
        // The S3 bucket must be where the backend looks for it, and the key goes with it.
        let region = aws_bootstrap_region(main, cat);
        if !region.is_empty() {
            p.settings
                .provider_settings
                .entry("aws".into())
                .or_default()
                .insert("region".into(), region);
        }
    }
    p
}

/// The field defaults a node dropped on the canvas starts with, abstract and per
/// provider: a mapping reads a provider field's value, not its declared default.
fn defaults(cat: &Catalog, resource_type: &str) -> (Config, BTreeMap<String, Config>) {
    let mut config = Config::new();
    let mut provider_config = BTreeMap::new();
    if let Some(def) = cat.resource(resource_type) {
        for f in &def.fields {
            if let Some(v) = f.default_value() {
                config.insert(f.name.clone(), v);
            }
        }
        for (pid, m) in &def.providers {
            let c: Config = m
                .fields
                .iter()
                .filter_map(|f| f.default_value().map(|v| (f.name.clone(), v)))
                .collect();
            provider_config.insert(pid.clone(), c);
        }
    }
    (config, provider_config)
}

fn node(cat: &Catalog, id: &str, name: &str, resource_type: &str) -> Node {
    let (config, provider_config) = defaults(cat, resource_type);
    Node {
        id: id.into(),
        name: name.into(),
        resource_type: resource_type.into(),
        config,
        provider_config,
        position: Default::default(),
        size: None,
        parent: None,
        manual: false,
        providers: Vec::new(),
        extra: Default::default(),
        classification: None,
        description: String::new(),
        owner: String::new(),
    }
}

/// The state bucket: an Object Storage node with versioning on, public access blocked
/// and plain HTTP refused, named exactly as the backend expects.
fn add_store(mini: &mut Project, main: &Project, cfg: &BackendConfig, cat: &Catalog) {
    let arg = |k: &str| Value::Str(cfg.args.get(k).cloned().unwrap_or_default());
    let mut n = node(cat, STORE_ID, &format!("{} state", main.name), "object_storage");
    n.config.insert("versioning".into(), Value::Bool(true));
    n.config.insert("block_public_access".into(), Value::Bool(true));
    n.config.insert("tls_only".into(), Value::Bool(true));
    match cfg.backend_type.as_str() {
        "s3" => {
            n.provider_config
                .entry("aws".into())
                .or_default()
                .insert("bucket_name".into(), arg("bucket"));
        }
        "gcs" => {
            n.provider_config
                .entry("gcp".into())
                .or_default()
                .insert("bucket_name".into(), arg("bucket"));
        }
        "azurerm" => {
            let azure = n.provider_config.entry("azure".into()).or_default();
            azure.insert("account_name".into(), arg("storage_account_name"));
            azure.insert("container_name".into(), arg("container_name"));
            // The resource group's mapping kebab-cases the display name; the backend
            // needs the exact name, so it is set as an extra argument (which wins).
            let rg_name = cfg.args.get("resource_group_name").cloned().unwrap_or_default();
            let mut extra = serde_json::Map::new();
            extra.insert("name".into(), serde_json::Value::String(rg_name.clone()));
            let (config, provider_config) = defaults(cat, "resource_group");
            let rg = Container {
                id: STORE_RG_ID.into(),
                name: rg_name,
                container_type: "resource_group".into(),
                config,
                provider_config,
                position: Default::default(),
                size: Default::default(),
                parent: None,
                manual: false,
                providers: Vec::new(),
                extra: [(
                    "azure".to_string(),
                    [("main".to_string(), extra)].into_iter().collect(),
                )]
                .into_iter()
                .collect(),
                classification: None,
                description: String::new(),
                owner: String::new(),
            };
            mini.containers.insert(rg.id.clone(), rg);
            n.parent = Some(STORE_RG_ID.into());
        }
        _ => {}
    }
    mini.nodes.insert(n.id.clone(), n);
}

/// The state key: the project's own Encryption Key entity, copied with its settings, so
/// it is generated by its own mapping (key policy included) in the bootstrap root.
fn add_key(mini: &mut Project, main: &Project, key: &str) {
    let Some(src) = main.nodes.get(key) else {
        return;
    };
    let mut n = src.clone();
    n.parent = None;
    n.providers.clear();
    mini.nodes.insert(n.id.clone(), n);
}

// ------------------------------------------------------------------ diagnostics

fn diag(entity: Option<&str>, severity: Severity, message: String) -> Diagnostic {
    Diagnostic {
        entity: entity.map(str::to_string),
        severity,
        code: Code::State,
        message,
        provider: None,
    }
}

/// Everything about state for one provider's export: the backend and the key setting
/// are valid, what Terraform cannot do, what the bootstrap root would refuse, and where a
/// secret the configuration generates ends up. `full` is the whole project, `layer` the
/// provider's layer of it.
pub fn checks(full: &Project, layer: &Project, cat: &Catalog, provider: &str, tool: Tool) -> Vec<Diagnostic> {
    let mut out = Vec::new();
    let s = &full.settings;
    let pname = cat
        .provider(provider)
        .map(|d| d.provider.display_name.clone())
        .unwrap_or(provider.to_string());

    // The backend.
    let backend = match &s.backend {
        None => None,
        Some(b) => match check_backend(b) {
            Ok(()) => Some(normalized(b)),
            Err(e) => {
                out.push(diag(
                    None,
                    Severity::Error,
                    format!("State backend: {e} (Settings ▸ State backend)"),
                ));
                None
            }
        },
    };
    let remote = backend.as_ref().filter(|b| b.backend_type != "local");
    if let Some(b) = remote {
        let kind = backend_kind(&b.backend_type).unwrap();
        if kind.provider.is_some_and(|bp| bp != provider) {
            let store = kind
                .provider
                .and_then(|bp| cat.provider(bp))
                .map(|d| d.provider.display_name.clone())
                .unwrap_or_default();
            out.push(diag(
                None,
                Severity::Info,
                format!(
                    "the {pname} export keeps its state in {} (backend \"{}\"): init and apply need {store} credentials as well, and its bootstrap root creates the store on {store}",
                    kind.display, b.backend_type
                ),
            ));
        }
    }

    // The key setting.
    let key = match s.state_encryption_key.as_deref() {
        None => None,
        Some(k) => {
            match full.entity(k) {
                Some(e) if e.resource_type == "encryption_key" => Some(e),
                Some(e) => {
                    let sev = if s.state_encryption && tool == Tool::OpenTofu {
                        Severity::Error
                    } else {
                        Severity::Warning
                    };
                    out.push(diag(
                    Some(e.id),
                    sev,
                    format!(
                        "the state encryption key \"{}\" is a {}, not an Encryption Key (Settings ▸ State encryption key)",
                        e.name, e.resource_type
                    ),
                ));
                    None
                }
                None => {
                    let sev = if s.state_encryption && tool == Tool::OpenTofu {
                        Severity::Error
                    } else {
                        Severity::Warning
                    };
                    out.push(diag(
                    None,
                    sev,
                    format!("the state encryption key \"{k}\" does not exist (Settings ▸ State encryption key)"),
                ));
                    None
                }
            }
        }
    };
    if key.is_some() && !s.state_encryption {
        out.push(diag(
            key.map(|k| k.id),
            Severity::Info,
            "is chosen as the state encryption key, but state encryption is off (Settings)".to_string(),
        ));
    }
    if s.state_encryption && tool == Tool::Terraform {
        out.push(diag(
            None,
            Severity::Warning,
            "state encryption needs OpenTofu: Terraform has no `encryption` block, so nothing is generated and the state stays unencrypted. Switch the tool to OpenTofu (Settings) to encrypt it".to_string(),
        ));
    }
    let plan = encryption_plan(layer, cat, provider, tool);
    if let Some(plan) = &plan {
        match (plan.source, key) {
            (KeySource::Passphrase, Some(k)) if layer.entity(k.id).is_none() => out.push(diag(
                Some(k.id),
                Severity::Info,
                format!(
                    "the state encryption key \"{}\" is not part of the {pname} layer, so the {pname} export encrypts its state with a passphrase (variable {PASSPHRASE_VAR})",
                    k.name
                ),
            )),
            (KeySource::Passphrase, Some(k)) => out.push(diag(
                Some(k.id),
                Severity::Info,
                format!(
                    "{pname} has no KMS key provider the export can use, so its state is encrypted with a passphrase (variable {PASSPHRASE_VAR}) rather than \"{}\". OpenTofu 1.10 had no Azure key provider; 1.12 has `azure_vault`, which the export does not use yet: the key would have to move to the bootstrap root together with its Key Vault",
                    k.name
                ),
            )),
            (KeySource::Passphrase, None) if matches!(provider, "aws" | "gcp") => out.push(diag(
                None,
                Severity::Info,
                format!(
                    "the state is encrypted with a passphrase (variable {PASSPHRASE_VAR}); choose an Encryption Key as the state encryption key (Settings) to use {} instead",
                    if provider == "aws" { "AWS KMS" } else { "Cloud KMS" }
                ),
            )),
            _ => {}
        }
        // A key other resources are encrypted with must be in their region.
        if let (KeySource::AwsKms, Some(k)) = (plan.source, &plan.key) {
            let bootstrap_region = plan.region.clone().unwrap_or_default();
            let main_region = aws_region(layer, cat);
            let used = layer.edges.iter().any(|e| &e.target == k);
            if used && !bootstrap_region.is_empty() && bootstrap_region != main_region {
                out.push(diag(
                    Some(k),
                    Severity::Warning,
                    format!(
                        "the bootstrap root creates this key in {bootstrap_region} (the S3 backend's region), but the resources encrypted with it are in {main_region}: KMS keys are regional, so they cannot use it. Keep the state bucket in {main_region}, or choose another key for the state"
                    ),
                ));
            }
        }
    }

    // What the bootstrap roots would refuse, reported here so the export's own gate
    // stops before writing half a configuration.
    for root in bootstrap_roots(layer, cat, provider, tool) {
        for d in crate::diagnostics::run(&root.project, cat, &root.provider) {
            if d.severity != Severity::Error {
                continue;
            }
            // The key's own problems are already reported on the canvas.
            if root
                .key
                .as_deref()
                .is_some_and(|k| d.entity.as_deref() == Some(k))
            {
                continue;
            }
            out.push(diag(
                None,
                Severity::Error,
                format!(
                    "State bootstrap ({}/): {} (Settings ▸ State backend)",
                    root.dir, d.message
                ),
            ));
        }
    }

    // Secrets the configuration itself puts into the state.
    let encrypted = plan.is_some();
    for e in layer.entities() {
        if e.manual {
            continue;
        }
        let Some(def) = cat.resource(e.resource_type) else {
            continue;
        };
        let Some(m) = cat.mapping(e.resource_type, provider) else {
            continue;
        };
        let fields = def.fields.iter().chain(m.fields.iter());
        for f in fields.filter(|f| f.state_secret) {
            let on = e
                .field(&f.name)
                .or_else(|| e.provider_field(provider, &f.name))
                .and_then(|v| v.as_bool())
                .or_else(|| f.default_value().and_then(|v| v.as_bool()))
                .unwrap_or(false);
            if !on {
                continue;
            }
            let what = format!("\"{}\" has '{}' on", e.name, f.label());
            let msg = match (remote, encrypted) {
                (None, false) => format!(
                    "{what}: the generated value is stored in plain text in local state; configure a remote backend and state encryption (Settings)"
                ),
                (None, true) => format!(
                    "{what}: the generated value is stored in local state (encrypted); configure a remote backend (Settings) so the only copy is not on this machine"
                ),
                (Some(b), false) => format!(
                    "{what}: the generated value is stored in plain text in the remote state ({} backend); turn on state encryption (Settings{})",
                    b.backend_type,
                    if tool == Tool::Terraform { "; it needs OpenTofu" } else { "" }
                ),
                (Some(_), true) => continue,
            };
            out.push(diag(Some(e.id), Severity::Warning, msg));
        }
    }
    out
}
