//! The ONLY place where Terraform and OpenTofu differ.
//!
//! Resource, variable and output generation never branch on the tool. Everything that
//! does differ — binary name, version constraint, registry source addresses, file
//! headers, whether the state can be encrypted — is expressed through `Profile`. What the
//! `backend` and `encryption` blocks contain is `crate::state`'s business; it asks
//! `supports_state_encryption` before writing the latter.

use ttg_core::Tool;

#[derive(Debug, Clone, Copy)]
pub struct Profile {
    pub tool: Tool,
}

impl Profile {
    pub fn new(tool: Tool) -> Self {
        Profile { tool }
    }

    /// Executable name on PATH.
    pub fn binary(&self) -> &'static str {
        match self.tool {
            Tool::Terraform => "terraform",
            Tool::OpenTofu => "tofu",
        }
    }

    pub fn display_name(&self) -> &'static str {
        self.tool.display_name()
    }

    /// `required_version` constraint. OpenTofu's first release was 1.6.0; the Terraform
    /// floor is the last MPL release so the output stays usable under both licences.
    pub fn required_version(&self) -> &'static str {
        match self.tool {
            Tool::Terraform => ">= 1.5.0",
            Tool::OpenTofu => ">= 1.6.0",
        }
    }

    /// Registry source address for `required_providers`. OpenTofu resolves short
    /// addresses against its own registry, but the explicit form documents intent and is
    /// what the OpenTofu docs recommend for canonical references.
    pub fn provider_source(&self, namespace: &str, name: &str) -> String {
        match self.tool {
            Tool::Terraform => format!("{namespace}/{name}"),
            Tool::OpenTofu => format!("registry.opentofu.org/{namespace}/{name}"),
        }
    }

    /// Registry web URL for humans (README).
    pub fn registry_url(&self, namespace: &str, name: &str) -> String {
        match self.tool {
            Tool::Terraform => {
                format!("https://registry.terraform.io/providers/{namespace}/{name}/latest/docs")
            }
            Tool::OpenTofu => {
                format!("https://search.opentofu.org/provider/{namespace}/{name}/latest")
            }
        }
    }

    /// Comment placed at the top of every generated file.
    pub fn file_header(&self, provider_display: &str) -> String {
        format!(
            "# Generated by TerraTofu GUI for {} — target provider: {}.\n\
             # This file is regenerated on export; hand edits will be overwritten.\n",
            self.display_name(),
            provider_display
        )
    }

    /// Whether the tool supports the `terraform { encryption {} }` state-encryption block
    /// (OpenTofu 1.7+; Terraform has no equivalent).
    pub fn supports_state_encryption(&self) -> bool {
        matches!(self.tool, Tool::OpenTofu)
    }
}
