//! The ONLY place where Terraform and OpenTofu differ.
//!
//! Resource, variable and output generation never branch on the tool. Everything that
//! does differ — binary name, version constraint, registry source addresses, file
//! headers, the OpenTofu-only state `encryption` block — is expressed through `Profile`.

use hcl::{Block, Expression, Traversal, Variable};
use ttg_core::{BackendConfig, Tool};

#[derive(Debug, Clone, Copy)]
pub struct Profile {
    pub tool: Tool,
}

impl Profile {
    pub fn new(tool: Tool) -> Self {
        Profile { tool }
    }

    /// Executable name on PATH.
    pub fn binary(&self) -> &'static str {
        match self.tool {
            Tool::Terraform => "terraform",
            Tool::OpenTofu => "tofu",
        }
    }

    pub fn display_name(&self) -> &'static str {
        self.tool.display_name()
    }

    /// `required_version` constraint. OpenTofu's first release was 1.6.0; the Terraform
    /// floor is the last MPL release so the output stays usable under both licences.
    pub fn required_version(&self) -> &'static str {
        match self.tool {
            Tool::Terraform => ">= 1.5.0",
            Tool::OpenTofu => ">= 1.6.0",
        }
    }

    /// Registry source address for `required_providers`. OpenTofu resolves short
    /// addresses against its own registry, but the explicit form documents intent and is
    /// what the OpenTofu docs recommend for canonical references.
    pub fn provider_source(&self, namespace: &str, name: &str) -> String {
        match self.tool {
            Tool::Terraform => format!("{namespace}/{name}"),
            Tool::OpenTofu => format!("registry.opentofu.org/{namespace}/{name}"),
        }
    }

    /// Registry web URL for humans (README).
    pub fn registry_url(&self, namespace: &str, name: &str) -> String {
        match self.tool {
            Tool::Terraform => {
                format!("https://registry.terraform.io/providers/{namespace}/{name}/latest/docs")
            }
            Tool::OpenTofu => {
                format!("https://search.opentofu.org/provider/{namespace}/{name}/latest")
            }
        }
    }

    /// Comment placed at the top of every generated file.
    pub fn file_header(&self, provider_display: &str) -> String {
        format!(
            "# Generated by TerraTofu GUI for {} — target provider: {}.\n\
             # This file is regenerated on export; hand edits will be overwritten.\n",
            self.display_name(),
            provider_display
        )
    }

    /// Whether the tool supports the `terraform { encryption {} }` state-encryption block.
    pub fn supports_state_encryption(&self) -> bool {
        matches!(self.tool, Tool::OpenTofu)
    }

    /// The `terraform { backend "<type>" { ... } }` block (both tools use the
    /// `terraform` keyword). Adds an OpenTofu `encryption` block when requested.
    pub fn backend_block(&self, backend: Option<&BackendConfig>, encrypt: bool) -> Option<Block> {
        let want_encrypt = encrypt && self.supports_state_encryption();
        if backend.is_none() && !want_encrypt {
            return None;
        }
        let mut b = Block::builder("terraform");
        if let Some(cfg) = backend {
            let mut bb = Block::builder("backend").add_label(cfg.backend_type.as_str());
            for (k, v) in &cfg.args {
                bb = bb.add_attribute((k.as_str(), v.as_str()));
            }
            b = b.add_block(bb.build());
        }
        if want_encrypt {
            let kp = Block::builder("key_provider")
                .add_label("pbkdf2")
                .add_label("main")
                .add_attribute(("passphrase", var("state_passphrase")))
                .build();
            let method = Block::builder("method")
                .add_label("aes_gcm")
                .add_label("main")
                .add_attribute((
                    "keys",
                    Expression::Traversal(Box::new(
                        Traversal::builder(Variable::unchecked("key_provider"))
                            .attr("pbkdf2")
                            .attr("main")
                            .build(),
                    )),
                ))
                .build();
            let state = Block::builder("state")
                .add_attribute((
                    "method",
                    Expression::Traversal(Box::new(
                        Traversal::builder(Variable::unchecked("method"))
                            .attr("aes_gcm")
                            .attr("main")
                            .build(),
                    )),
                ))
                .build();
            b = b.add_block(
                Block::builder("encryption")
                    .add_block(kp)
                    .add_block(method)
                    .add_block(state)
                    .build(),
            );
        }
        Some(b.build())
    }
}

fn var(name: &str) -> Expression {
    Expression::Traversal(Box::new(
        Traversal::builder(Variable::unchecked("var")).attr(name).build(),
    ))
}
