//! Optional shell-out to `terraform` / `tofu` to validate an exported directory.
//! Neither binary is a dependency of the application: if it is not on PATH the caller
//! gets `BinaryNotFound` and can show the command to run by hand.

use crate::tool::Profile;
use std::path::Path;
use std::process::Command;
use ttg_core::Tool;

#[derive(Debug, Clone)]
pub enum Outcome {
    BinaryNotFound {
        binary: String,
    },
    Ran {
        success: bool,
        init_output: String,
        validate_output: String,
    },
}

impl Outcome {
    pub fn summary(&self) -> String {
        match self {
            Outcome::BinaryNotFound { binary } => format!(
                "`{binary}` not found on PATH. Run `{binary} init -backend=false && {binary} validate` in the export directory."
            ),
            Outcome::Ran { success: true, .. } => "validate passed".into(),
            Outcome::Ran { success: false, validate_output, init_output, .. } => {
                format!("validate FAILED\n{init_output}\n{validate_output}")
            }
        }
    }
}

/// Locate the tool binary: `TTG_TOOL_DIR`, then PATH, then well-known per-user and
/// package-manager install locations that are often not on PATH for GUI processes.
pub fn find_binary(tool: Tool) -> Option<std::path::PathBuf> {
    let name = Profile::new(tool).binary();
    let exe_names: Vec<String> = if cfg!(windows) {
        vec![format!("{name}.exe"), name.to_string()]
    } else {
        vec![name.to_string()]
    };
    let mut dirs: Vec<std::path::PathBuf> = Vec::new();
    if let Some(d) = std::env::var_os("TTG_TOOL_DIR") {
        dirs.push(d.into());
    }
    if let Some(path) = std::env::var_os("PATH") {
        dirs.extend(std::env::split_paths(&path));
    }
    if let Some(local) = std::env::var_os("LOCALAPPDATA") {
        let local = std::path::PathBuf::from(local);
        dirs.push(local.join("Programs").join("OpenTofu"));
        dirs.push(local.join("Programs").join("Terraform"));
        dirs.push(local.join("Microsoft").join("WinGet").join("Links"));
    }
    if let Some(home) = std::env::var_os("HOME").or_else(|| std::env::var_os("USERPROFILE")) {
        let home = std::path::PathBuf::from(home);
        dirs.push(home.join(".local").join("bin"));
        dirs.push(home.join("bin"));
    }
    for d in [
        "C:\\Program Files\\OpenTofu",
        "C:\\Program Files\\Terraform",
        "C:\\ProgramData\\chocolatey\\bin",
        "/usr/local/bin",
        "/opt/homebrew/bin",
        "/usr/bin",
    ] {
        dirs.push(d.into());
    }
    for dir in dirs {
        for n in &exe_names {
            let candidate = dir.join(n);
            if candidate.is_file() {
                return Some(candidate);
            }
        }
    }
    None
}

/// Provider plugin cache shared by every validate run. Honours `TF_PLUGIN_CACHE_DIR` if
/// the user already set one; otherwise a per-user cache directory is created.
pub fn plugin_cache_dir() -> std::path::PathBuf {
    if let Some(d) = std::env::var_os("TF_PLUGIN_CACHE_DIR") {
        return d.into();
    }
    let base = std::env::var_os("LOCALAPPDATA")
        .map(std::path::PathBuf::from)
        .or_else(|| std::env::var_os("XDG_CACHE_HOME").map(std::path::PathBuf::from))
        .or_else(|| std::env::var_os("HOME").map(|h| std::path::PathBuf::from(h).join(".cache")))
        .unwrap_or_else(std::env::temp_dir);
    let dir = base.join("terratofu-gui").join("plugin-cache");
    let _ = std::fs::create_dir_all(&dir);
    dir
}

/// Write (or refresh) the private CLI config next to the cache. Returns `None` if the
/// file cannot be written, in which case init still works, just without the cache.
fn cli_config_file(cache: &Path) -> Option<std::path::PathBuf> {
    let path = cache.parent()?.join("validate.tfrc");
    let cache_str = cache.to_string_lossy().replace('\\', "/");
    let body = format!(
        "# Generated by TerraTofu GUI for its `validate` runs only.\n\
         plugin_cache_dir = \"{cache_str}\"\n\
         plugin_cache_may_break_dependency_lock_file = true\n"
    );
    let stale = std::fs::read_to_string(&path).ok().as_deref() != Some(body.as_str());
    if stale {
        std::fs::write(&path, body).ok()?;
    }
    Some(path)
}

/// Run `init -backend=false` then `validate` in `dir`.
pub fn run(dir: &Path, tool: Tool) -> Outcome {
    let profile = Profile::new(tool);
    let Some(bin) = find_binary(tool) else {
        return Outcome::BinaryNotFound {
            binary: profile.binary().to_string(),
        };
    };
    // Share downloaded provider plugins across runs; without this every validate
    // re-downloads hundreds of megabytes of provider binaries. Both tools only consult
    // the cache for providers already pinned in `.terraform.lock.hcl`, which a fresh
    // export never has, so a private CLI config for the subprocess opts into using the
    // cache anyway (`plugin_cache_may_break_dependency_lock_file`). The user's own CLI
    // config is untouched: the env var only applies to this child process.
    let cache = plugin_cache_dir();
    let cli_config = cli_config_file(&cache);
    let mut init_cmd = Command::new(&bin);
    init_cmd
        .args(["init", "-backend=false", "-input=false", "-no-color"])
        .env("TF_PLUGIN_CACHE_DIR", &cache)
        .current_dir(dir);
    if let Some(cfg) = &cli_config {
        init_cmd.env("TF_CLI_CONFIG_FILE", cfg);
        init_cmd.env("TOFU_CLI_CONFIG_FILE", cfg);
    }
    let init = init_cmd.output();
    let (init_ok, init_output) = match init {
        Ok(o) => (
            o.status.success(),
            format!(
                "{}{}",
                String::from_utf8_lossy(&o.stdout),
                String::from_utf8_lossy(&o.stderr)
            ),
        ),
        Err(e) => (false, format!("failed to run init: {e}")),
    };
    if !init_ok {
        return Outcome::Ran {
            success: false,
            init_output,
            validate_output: String::new(),
        };
    }
    let val = Command::new(&bin)
        .args(["validate", "-no-color"])
        .current_dir(dir)
        .output();
    match val {
        Ok(o) => Outcome::Ran {
            success: o.status.success(),
            init_output,
            validate_output: format!(
                "{}{}",
                String::from_utf8_lossy(&o.stdout),
                String::from_utf8_lossy(&o.stderr)
            ),
        },
        Err(e) => Outcome::Ran {
            success: false,
            init_output,
            validate_output: format!("failed to run validate: {e}"),
        },
    }
}
