//! `ttg-schema` — a compact, bundled index of the Terraform provider schemas.
//!
//! The curated catalog (`ttg-catalog`) describes *portable* concepts by hand. This crate
//! carries the other side: every resource the AWS and Azure providers actually expose,
//! with every argument and nested block, as reported by `tofu providers schema -json`.
//! It powers the "Advanced arguments" editor on curated resources, the native
//! provider-resource palette, schema validation of extra arguments, and a test that keeps
//! the curated definitions honest against the real providers.
//!
//! The index is generated by `ttg schema refresh` (see `ttg-cli`), gzipped and bundled
//! into the binary; a refreshed copy under the user's data directory takes precedence.

use serde::{Deserialize, Serialize};
use std::collections::BTreeMap;
use std::io::Read;
use std::sync::OnceLock;

/// The bundled index (generated by `ttg schema refresh --out crates/ttg-schema/data/index.json.gz`).
const BUNDLED: &[u8] = include_bytes!("../data/index.json.gz");

#[derive(Debug, Clone, Serialize, Deserialize, Default)]
pub struct SchemaIndex {
    /// ISO date the index was generated.
    #[serde(default)]
    pub generated: String,
    /// Catalog provider id (`aws`, `azure`) -> its schema.
    #[serde(default)]
    pub providers: BTreeMap<String, ProviderSchema>,
}

#[derive(Debug, Clone, Serialize, Deserialize, Default)]
pub struct ProviderSchema {
    /// Registry source, e.g. `hashicorp/aws`.
    #[serde(default)]
    pub source: String,
    /// Provider version the index was generated from.
    #[serde(default)]
    pub version: String,
    /// Resource type -> schema.
    #[serde(default)]
    pub resources: BTreeMap<String, BlockSchema>,
}

/// One block's shape: attributes and nested block types.
#[derive(Debug, Clone, Serialize, Deserialize, Default)]
pub struct BlockSchema {
    #[serde(default, rename = "a", skip_serializing_if = "BTreeMap::is_empty")]
    pub attributes: BTreeMap<String, AttrSchema>,
    #[serde(default, rename = "b", skip_serializing_if = "BTreeMap::is_empty")]
    pub blocks: BTreeMap<String, NestedSchema>,
}

/// `[type, required, optional, computed, sensitive, description]`
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct AttrSchema(pub String, pub u8, pub u8, pub u8, pub u8, pub String);

impl AttrSchema {
    /// The HCL type as the provider reports it, JSON-encoded (`"string"`, `["list","string"]`, …).
    pub fn type_json(&self) -> &str {
        &self.0
    }
    pub fn required(&self) -> bool {
        self.1 == 1
    }
    pub fn optional(&self) -> bool {
        self.2 == 1
    }
    pub fn computed(&self) -> bool {
        self.3 == 1
    }
    pub fn sensitive(&self) -> bool {
        self.4 == 1
    }
    pub fn description(&self) -> &str {
        &self.5
    }
    /// Read-only attribute (computed and not settable).
    pub fn read_only(&self) -> bool {
        self.computed() && !self.optional() && !self.required()
    }
    /// Coarse kind for editors and validation.
    pub fn kind(&self) -> TypeKind {
        TypeKind::from_type_json(&self.0)
    }
}

/// `[nesting, min_items, max_items, block]`
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct NestedSchema(pub String, pub u64, pub u64, pub BlockSchema);

impl NestedSchema {
    /// `single` | `list` | `set` | `map` | `group`
    pub fn nesting(&self) -> &str {
        &self.0
    }
    pub fn min_items(&self) -> u64 {
        self.1
    }
    pub fn max_items(&self) -> u64 {
        self.2
    }
    pub fn block(&self) -> &BlockSchema {
        &self.3
    }
    pub fn required(&self) -> bool {
        self.1 > 0
    }
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum TypeKind {
    String,
    Number,
    Bool,
    List,
    Set,
    Map,
    Object,
    Dynamic,
}

impl TypeKind {
    pub fn from_type_json(t: &str) -> TypeKind {
        match t.trim_matches('"') {
            "string" => return TypeKind::String,
            "number" => return TypeKind::Number,
            "bool" => return TypeKind::Bool,
            "dynamic" => return TypeKind::Dynamic,
            _ => {}
        }
        if t.starts_with("[\"list\"") {
            TypeKind::List
        } else if t.starts_with("[\"set\"") {
            TypeKind::Set
        } else if t.starts_with("[\"map\"") {
            TypeKind::Map
        } else if t.starts_with("[\"object\"") {
            TypeKind::Object
        } else {
            TypeKind::Dynamic
        }
    }
    pub fn label(self) -> &'static str {
        match self {
            TypeKind::String => "string",
            TypeKind::Number => "number",
            TypeKind::Bool => "bool",
            TypeKind::List => "list",
            TypeKind::Set => "set",
            TypeKind::Map => "map",
            TypeKind::Object => "object",
            TypeKind::Dynamic => "any",
        }
    }
}

impl BlockSchema {
    /// Does this block accept `name` as an attribute or a nested block?
    pub fn has(&self, name: &str) -> bool {
        self.attributes.contains_key(name) || self.blocks.contains_key(name)
    }
    /// Names of every settable argument (attributes that are not read-only, and blocks).
    pub fn settable(&self) -> Vec<&str> {
        let mut v: Vec<&str> = self
            .attributes
            .iter()
            .filter(|(_, a)| !a.read_only())
            .map(|(k, _)| k.as_str())
            .chain(self.blocks.keys().map(|k| k.as_str()))
            .collect();
        v.sort();
        v
    }
    /// Required attributes and blocks.
    pub fn required(&self) -> Vec<&str> {
        let mut v: Vec<&str> = self
            .attributes
            .iter()
            .filter(|(_, a)| a.required())
            .map(|(k, _)| k.as_str())
            .chain(
                self.blocks
                    .iter()
                    .filter(|(_, b)| b.required())
                    .map(|(k, _)| k.as_str()),
            )
            .collect();
        v.sort();
        v
    }
}

impl ProviderSchema {
    pub fn resource(&self, tf_type: &str) -> Option<&BlockSchema> {
        self.resources.get(tf_type)
    }
    /// Resource types containing every whitespace-separated term of `query` (case-insensitive).
    pub fn search(&self, query: &str, limit: usize) -> Vec<&str> {
        let terms: Vec<String> = query.split_whitespace().map(|t| t.to_lowercase()).collect();
        let mut out: Vec<&str> = self
            .resources
            .keys()
            .filter(|k| terms.iter().all(|t| k.contains(t.as_str())))
            .map(|k| k.as_str())
            .collect();
        // Prefer shorter names (closer matches) for the same terms.
        out.sort_by_key(|k| (k.len(), *k));
        out.truncate(limit);
        out
    }
}

impl SchemaIndex {
    pub fn provider(&self, id: &str) -> Option<&ProviderSchema> {
        self.providers.get(id)
    }
    /// Schema of a resource type on a provider.
    pub fn resource(&self, provider: &str, tf_type: &str) -> Option<&BlockSchema> {
        self.providers.get(provider)?.resources.get(tf_type)
    }
    pub fn resource_count(&self) -> usize {
        self.providers.values().map(|p| p.resources.len()).sum()
    }

    /// Parse a gzipped JSON index.
    pub fn from_gzip(bytes: &[u8]) -> Result<SchemaIndex, String> {
        let mut dec = flate2::read::GzDecoder::new(bytes);
        let mut s = String::new();
        dec.read_to_string(&mut s).map_err(|e| format!("gunzip: {e}"))?;
        serde_json::from_str(&s).map_err(|e| format!("parse: {e}"))
    }

    pub fn to_gzip(&self) -> Result<Vec<u8>, String> {
        use std::io::Write;
        let json = serde_json::to_string(self).map_err(|e| e.to_string())?;
        let mut enc = flate2::write::GzEncoder::new(Vec::new(), flate2::Compression::best());
        enc.write_all(json.as_bytes()).map_err(|e| e.to_string())?;
        enc.finish().map_err(|e| e.to_string())
    }
}

/// Where a refreshed index is stored per user (`ttg schema refresh` without `--out`).
pub fn user_index_path() -> Option<std::path::PathBuf> {
    let base = std::env::var_os("LOCALAPPDATA")
        .map(std::path::PathBuf::from)
        .or_else(|| std::env::var_os("XDG_DATA_HOME").map(std::path::PathBuf::from))
        .or_else(|| std::env::var_os("HOME").map(|h| std::path::PathBuf::from(h).join(".local/share")))?;
    Some(base.join("terratofu-gui").join("schema-index.json.gz"))
}

static INDEX: OnceLock<SchemaIndex> = OnceLock::new();

/// The process-wide index: a per-user refreshed copy if present and readable, else the
/// bundled one. Parsed once, lazily (a few hundred milliseconds).
pub fn index() -> &'static SchemaIndex {
    INDEX.get_or_init(|| {
        if let Some(p) = user_index_path() {
            if let Ok(bytes) = std::fs::read(&p) {
                if let Ok(idx) = SchemaIndex::from_gzip(&bytes) {
                    if !idx.providers.is_empty() {
                        return idx;
                    }
                }
            }
        }
        SchemaIndex::from_gzip(BUNDLED).unwrap_or_default()
    })
}

/// Which index `index()` would use: `"user"` or `"bundled"`.
pub fn index_source() -> &'static str {
    if user_index_path().is_some_and(|p| p.is_file()) {
        "user"
    } else {
        "bundled"
    }
}

/// Build an index from the raw `providers schema -json` output. `provider_ids` maps the
/// registry source name (`aws`, `azurerm`) to the catalog provider id (`aws`, `azure`).
pub fn compact_from_tool_json(
    raw: &str,
    provider_ids: &BTreeMap<String, String>,
) -> Result<SchemaIndex, String> {
    let v: serde_json::Value = serde_json::from_str(raw).map_err(|e| format!("parse tool output: {e}"))?;
    let mut idx = SchemaIndex {
        generated: today(),
        providers: BTreeMap::new(),
    };
    let Some(ps) = v.get("provider_schemas").and_then(|p| p.as_object()) else {
        return Err("no provider_schemas in tool output".into());
    };
    for (addr, ps) in ps {
        // registry.opentofu.org/hashicorp/aws -> aws
        let name = addr.rsplit('/').next().unwrap_or(addr).to_string();
        let Some(id) = provider_ids.get(&name) else {
            continue;
        };
        let mut prov = ProviderSchema {
            source: addr.split_once('/').map(|x| x.1).unwrap_or(addr).to_string(),
            version: String::new(),
            resources: BTreeMap::new(),
        };
        if let Some(rs) = ps.get("resource_schemas").and_then(|r| r.as_object()) {
            for (rname, rs) in rs {
                if let Some(b) = rs.get("block") {
                    prov.resources.insert(rname.clone(), compact_block(b));
                }
            }
        }
        idx.providers.insert(id.clone(), prov);
    }
    Ok(idx)
}

fn compact_block(b: &serde_json::Value) -> BlockSchema {
    let mut out = BlockSchema::default();
    if let Some(attrs) = b.get("attributes").and_then(|a| a.as_object()) {
        for (k, a) in attrs {
            let ty = a
                .get("type")
                .map(|t| {
                    if let Some(s) = t.as_str() {
                        s.to_string()
                    } else {
                        t.to_string()
                    }
                })
                .unwrap_or_else(|| "dynamic".into());
            let flag = |n: &str| u8::from(a.get(n).and_then(|x| x.as_bool()).unwrap_or(false));
            let mut desc = a
                .get("description")
                .and_then(|d| d.as_str())
                .unwrap_or("")
                .to_string();
            if desc.len() > 200 {
                let mut cut = 200;
                while !desc.is_char_boundary(cut) {
                    cut -= 1;
                }
                desc.truncate(cut);
                desc.push('…');
            }
            out.attributes.insert(
                k.clone(),
                AttrSchema(
                    ty,
                    flag("required"),
                    flag("optional"),
                    flag("computed"),
                    flag("sensitive"),
                    desc,
                ),
            );
        }
    }
    if let Some(blocks) = b.get("block_types").and_then(|a| a.as_object()) {
        for (k, bt) in blocks {
            let nesting = bt
                .get("nesting_mode")
                .and_then(|n| n.as_str())
                .unwrap_or("list")
                .to_string();
            let min = bt.get("min_items").and_then(|n| n.as_u64()).unwrap_or(0);
            let max = bt.get("max_items").and_then(|n| n.as_u64()).unwrap_or(0);
            let inner = bt.get("block").map(compact_block).unwrap_or_default();
            out.blocks
                .insert(k.clone(), NestedSchema(nesting, min, max, inner));
        }
    }
    out
}

fn today() -> String {
    // No chrono dependency: derive the date from the system clock.
    let secs = std::time::SystemTime::now()
        .duration_since(std::time::UNIX_EPOCH)
        .map(|d| d.as_secs())
        .unwrap_or(0);
    let days = secs / 86_400;
    // Civil-from-days (Howard Hinnant).
    let z = days as i64 + 719_468;
    let era = z.div_euclid(146_097);
    let doe = z - era * 146_097;
    let yoe = (doe - doe / 1460 + doe / 36_524 - doe / 146_096) / 365;
    let y = yoe + era * 400;
    let doy = doe - (365 * yoe + yoe / 4 - yoe / 100);
    let mp = (5 * doy + 2) / 153;
    let d = doy - (153 * mp + 2) / 5 + 1;
    let m = if mp < 10 { mp + 3 } else { mp - 9 };
    let y = if m <= 2 { y + 1 } else { y };
    format!("{y:04}-{m:02}-{d:02}")
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn bundled_index_loads_and_has_both_providers() {
        let idx = index();
        assert!(idx.providers.contains_key("aws"), "aws missing");
        assert!(idx.providers.contains_key("azure"), "azure missing");
        assert!(idx.resource("aws", "aws_s3_bucket").is_some());
        assert!(idx.resource("azure", "azurerm_storage_account").is_some());
        let sqs = idx.resource("aws", "aws_sqs_queue").unwrap();
        assert!(sqs.attributes["name"].optional());
        assert_eq!(sqs.attributes["name"].kind(), TypeKind::String);
        assert!(sqs.attributes["arn"].read_only());
        let fa = idx.resource("azure", "azurerm_linux_function_app").unwrap();
        assert!(fa.blocks.contains_key("site_config"));
        assert!(fa.blocks["site_config"].required());
    }

    #[test]
    fn search_ranks_short_names_first() {
        let aws = index().provider("aws").unwrap();
        let hits = aws.search("sqs queue", 5);
        assert_eq!(hits.first().copied(), Some("aws_sqs_queue"));
    }

    #[test]
    fn type_kinds() {
        assert_eq!(TypeKind::from_type_json("string"), TypeKind::String);
        assert_eq!(TypeKind::from_type_json("[\"list\",\"string\"]"), TypeKind::List);
        assert_eq!(TypeKind::from_type_json("[\"map\",\"string\"]"), TypeKind::Map);
        assert_eq!(
            TypeKind::from_type_json("[\"object\",{\"a\":\"string\"}]"),
            TypeKind::Object
        );
    }
}
